// THIS IS GENERATED BY THE PREPROCESSOR
// THIS IS THE RTTI FOR THE ENTIRE PROGRAM

#ifndef GENERATED_PROGRAM_TYPES_H
#define GENERATED_PROGRAM_TYPES_H

enum GENERATED_program_type_t {
	TYPE_sys_handle_t,
	TYPE_string_t,
	TYPE_u64,
	TYPE_bool8,
	TYPE_file_t,
	TYPE_mapped_file_t,
	TYPE_file_data_t,
	TYPE_u32,
	TYPE_overlap_io_data_t,
	TYPE_visit_files_pfn_t,
	TYPE_void,
	TYPE_visit_file_data_t,
};
#endif // GENERATED_PROGRAM_TYPES_H
