// THIS IS GENERATED BY THE PREPROCESSOR
// THIS IS THE RTTI FOR THE ENTIRE PROGRAM

#ifndef GENERATED_PROGRAM_TYPES_H
#define GENERATED_PROGRAM_TYPES_H

#include <preprocessor_type_data.h>

enum GENERATED_program_types_t {
	TYPE_vec2,
	TYPE_global_context,
	TYPE_bool8,
	TYPE_memory_arena_t,
	TYPE_threadpool_t,
};

struct type_info_global_context {
	const char *name;
	u32 type;
	u32 member_count;
	struct members {
		type_info_member_t is_initialized;
		type_info_member_t running;
		type_info_member_t context_arena;
		type_info_member_t temporary_arena;
		type_info_member_t main_threadpool;
	}members;
};


const static type_info_global_context type_info_global_context = {
	.name = "global_context",
	.type = TYPE_global_context,
	.members = {
		.is_initialized = {.name = "is_initialized", .type = TYPE_bool8, .offset = offsetof(global_context, is_initialized), .size = sizeof(bool8)},
		.running = {.name = "running", .type = TYPE_bool8, .offset = offsetof(global_context, running), .size = sizeof(bool8)},
		.context_arena = {.name = "context_arena", .type = TYPE_memory_arena_t, .offset = offsetof(global_context, context_arena), .size = sizeof(memory_arena_t)},
		.temporary_arena = {.name = "temporary_arena", .type = TYPE_memory_arena_t, .offset = offsetof(global_context, temporary_arena), .size = sizeof(memory_arena_t)},
		.main_threadpool = {.name = "main_threadpool", .type = TYPE_threadpool_t, .offset = offsetof(global_context, main_threadpool), .size = sizeof(threadpool_t)},
	}
};

#endif // GENERATED_PROGRAM_TYPES_H

