/* ========================================================================
   $File: slang_reflector.cpp $
   $Date: April 21 2026 01:56 am $
   $Revision: $
   $Creator: Justin Lewis $
   ======================================================================== */
#include <c_types.h>
#include <c_base.h>

#define DYNARRAY_IMPLEMENTATION 
#define HASH_TABLE_IMPLEMENTATION
#define PROGRAM_FLAG_HANDLER_IMPLEMENTATION

#include <c_hash_table.h>
#include <c_dynarray.h>
#include <c_program_flag_handler.h>

#include <p_platform_data.cpp>
#include <c_memory_arena.cpp>
#include <c_zone_allocator.cpp>
#include <c_string.cpp>
#include <c_global_context.cpp>
#include <c_file_api.cpp>
#include <c_file_watcher.cpp>
#include <c_threadpool.cpp>
#include <c_tokenizer.cpp>

struct slang_reflector_module_t
{
    tokenizer_t      tokenizer; 
    memory_arena_t   file_arena;
    string_builder_t new_file_builder;
    string_t         source_file;
};

struct file_manager_t
{
    HashTable_t(string_t) loaded_files;
};

FILE_WATCHER_CALLBACK(shader_file_callback)
{
    file_manager_t *file_manager = (file_manager_t*)user_data;

    string_t fullname = change->full_path;
    string_t filename = c_string_get_filename_from_path_and_ext(change->full_path);
    string_t file_ext = c_string_get_file_ext_from_path(change->full_path);
    if(c_string_compare(file_ext, STR("slang")))
    {
        c_threadpool_push_work_order(&global_context->main_threadpool, [file_manager, filename, fullname]() {
             string_t *file_data = c_hash_table_get_value_ptr(&file_manager->loaded_files, filename);
             if(file_data->count > 0)
             {
                 *file_data = c_file_read_entirety(fullname);
             }

             slang_reflector_module_t module = {};
             module.file_arena  = c_arena_create(MB(1));
             module.tokenizer   = tokenizer_t{*file_data};
             module.source_file = *file_data;
             c_string_builder_init(&module.new_file_builder, MB(5));

             c_string_builder_append_data(&module.new_file_builder, STR("// THIS FILE IS AUTO GENERATED BY THE SLANG REFLECTOR...\n// DO NOT EDIT!!!!!\n\n"));

             tokenizer_t *tokenizer = &module.tokenizer;
             while(tokenizer->data.count > 0)
             {
             token_data_t token = c_tokenizer_get_next_token(tokenizer);
             switch(token.type)
             {
                 case TT_HashTag:
                 {
                     token_data_t preprocessor_token = c_tokenizer_get_next_token(tokenizer);
                     if(preprocessor_token.type == TT_Identifier)
                     {
                         // NOTE(Sleepster): Eat the "<" character so we can get the filename
                         c_tokenizer_get_next_token(tokenizer);
                         if(c_string_compare(preprocessor_token.string, STR("include")))
                         {
                             token_data_t filename = c_tokenizer_get_next_token(tokenizer);

                             // NOTE(Sleepster): Eat the ">" character... 
                             c_tokenizer_get_next_token(tokenizer);

                             string_t included_file = c_file_read_entirety(fullname);

                             c_string_builder_append_data(&module.new_file_builder, STR("// FROM INCLUDED FILE: "));
                             c_string_builder_append_data(&module.new_file_builder, filename.string);
                             c_string_builder_append_data(&module.new_file_builder, STR("\n"));
                             c_string_builder_append_data(&module.new_file_builder, STR("#line 1 \""));
                             c_string_builder_append_data(&module.new_file_builder, filename.string);
                             c_string_builder_append_data(&module.new_file_builder, STR("\"\n"));
                             c_string_builder_append_data(&module.new_file_builder, included_file);
                             c_string_builder_append_data(&module.new_file_builder, STR("// END OF INCLUDED FILE\n"));

                             module.source_file = tokenizer->data;
                         }
                     }
                 }break;
             }
             }

             c_string_builder_append_data(&module.new_file_builder, STR("#line 1 \""));
             c_string_builder_append_data(&module.new_file_builder, STR("basic_triangle.slang\""));
             c_string_builder_append_data(&module.new_file_builder, module.source_file);

             file_t new_file = c_file_open(STR("../build/test_concatted_file.slang"), true);
             c_string_builder_dump_to_file(&new_file, &module.new_file_builder);
        }, null);
    }
}

int
main(int argc, char **argv)
{
    c_global_context_init();

    u32 thread_count = sys_get_thread_count();
    c_threadpool_init(&global_context->main_threadpool, thread_count, MB(1), true);

    char  **shader_directory = c_program_flag_add_string("shader_directory_path", "shaders/", "This is the location that the preprocessor will search for shaders when a #include directive is found.\n");
    char  **output_directory = c_program_flag_add_string("shader_output_dir", "../build/", "This is the output location");
    bool32 *help             = c_program_flag_add_bool32("help", false, "Displays the help message...\n");
    if(argc > 1)
    {
        c_program_flag_parse_args(argc, argv);
        if(*help == true)
        {
            c_program_flag_print_flag_list();
        }
    }
    
    file_manager_t file_manager = {};
    c_hash_table_init(&file_manager.loaded_files, 2048);
        
    file_watcher_t watcher = c_file_watcher_create(FWC_EVENT_ALL, true, shader_file_callback, &file_manager, false);
    c_file_watcher_add_path(&watcher, STR(*shader_directory));
    c_file_watcher_issue_check_over_all_paths(&watcher);

    c_threadpool_flush_work_orders(&global_context->main_threadpool);

    return(0);
}
