/* ========================================================================
   $File: slang_reflector.cpp $
   $Date: April 21 2026 01:56 am $
   $Revision: $
   $Creator: Justin Lewis $
   ======================================================================== */
#include <c_types.h>
#include <c_base.h>

#define DYNARRAY_IMPLEMENTATION 
#define HASH_TABLE_IMPLEMENTATION
#define PROGRAM_FLAG_HANDLER_IMPLEMENTATION

#include <c_hash_table.h>
#include <c_dynarray.h>
#include <c_program_flag_handler.h>

#include <c_global_context.cpp>
#include <c_file_api.cpp>
#include <p_platform_data.cpp>
#include <c_memory_arena.cpp>
#include <c_zone_allocator.cpp>
#include <c_string.cpp>
#include <c_threadpool.cpp>
#include <c_tokenizer.cpp>

struct slang_reflector_module_t
{
    tokenizer_t      tokenizer; 
    memory_arena_t   file_arena;
    string_builder_t new_file_builder;
    string_t         source_file;
};

struct file_manager_t
{
    HashTable_t(string_t) loaded_files;
    string_t              shader_directory;
    string_t              output_directory;
};

VISIT_FILES(shader_file_callback)
{
    file_manager_t *file_manager = (file_manager_t*)user_data;

    string_t fullname = visit_file_data->fullname;
    string_t filename = visit_file_data->filename;
    string_t file_ext = c_string_get_file_ext_from_path(filename);
    if(c_string_compare(file_ext, STR(".slang")) || 
       c_string_compare(file_ext, STR(".slm")))
    {
        c_threadpool_push_work_order(&global_context->main_threadpool, [file_manager, filename, fullname]() {
             string_t *file_data = c_hash_table_get_value_ptr(&file_manager->loaded_files, filename);
             if(file_data->count == 0)
             {
                 *file_data = c_file_read_entirety(fullname);
             }

             slang_reflector_module_t module = {};
             module.file_arena  = c_arena_create(MB(1));
             module.tokenizer   = tokenizer_t{*file_data};
             module.source_file = *file_data;
             c_string_builder_init(&module.new_file_builder, MB(5));
             c_string_builder_append_data(&module.new_file_builder, STR("// THIS FILE IS AUTO GENERATED BY THE SLANG REFLECTOR...\n// DO NOT EDIT!!!!!\n\n"));

             tokenizer_t *tokenizer = &module.tokenizer;
             while(tokenizer->data.count > 0)
             {
                 token_data_t token = c_tokenizer_get_next_token(tokenizer);
                 switch(token.type)
                 {
                     case TT_HashTag:
                     {
                         token_data_t preprocessor_token = c_tokenizer_get_next_token(tokenizer);
                         if(preprocessor_token.type == TT_Identifier)
                         {
                             // NOTE(Sleepster): Eat the "<" character so we can get the filename
                             c_tokenizer_get_next_token(tokenizer);
                             if(c_string_compare(preprocessor_token.string, STR("include")))
                             {
                                 token_data_t included_filename_token = c_tokenizer_get_next_token(tokenizer);
                                 string_t included_filename = c_string_concat(&global_context->temporary_arena, file_manager->shader_directory, STR("/"));
                                          included_filename = c_string_concat(&global_context->temporary_arena, included_filename, c_string_make_copy(&global_context->temporary_arena, included_filename_token.string));

                                 // NOTE(Sleepster): Eat the ">" character... 
                                 c_tokenizer_get_next_token(tokenizer);

                                 string_t *included_file = c_hash_table_get_value_ptr(&file_manager->loaded_files, fullname);
                                 if(included_file->count == 0)
                                 {
                                     *included_file = c_file_read_entirety(included_filename);
                                 }

                                 c_string_builder_append_data(&module.new_file_builder,  STR("// FROM INCLUDED FILE: "));
                                 c_string_builder_append_data(&module.new_file_builder,  included_filename);
                                 c_string_builder_append_data(&module.new_file_builder,  STR("\n"));
                                 c_string_builder_append_data(&module.new_file_builder,  STR("#line 1 \""));
                                 c_string_builder_append_data(&module.new_file_builder,  included_filename);
                                 c_string_builder_append_data(&module.new_file_builder,  STR("\"\n"));
                                 c_string_builder_append_data(&module.new_file_builder, *included_file);
                                 c_string_builder_append_data(&module.new_file_builder,  STR("// END OF INCLUDED FILE\n"));

                                 module.source_file = tokenizer->data;
                             }
                         }
                     }break;
                 }
             }

             c_string_builder_append_data(&module.new_file_builder, STR("#line 1 \""));
             c_string_builder_append_data(&module.new_file_builder, filename);
             c_string_builder_append_data(&module.new_file_builder, STR("\"\n"));
             c_string_builder_append_data(&module.new_file_builder, module.source_file);

             string_t output_file = c_string_concat(&global_context->temporary_arena, file_manager->output_directory, filename);
             file_t new_file = c_file_open(output_file, true);
             c_string_builder_dump_to_file(&new_file, &module.new_file_builder);

             log_info("Wrote file: '%.*s' out...\n", output_file.count, C_STR(output_file));
        }, null);
    }
}

int
main(int argc, char **argv)
{
    c_global_context_init();

    u32 thread_count = sys_get_thread_count();
    c_threadpool_init(&global_context->main_threadpool, thread_count, MB(1), true);

    char  **shader_directory = c_program_flag_add_string("-shader_directory_path", "shaders/", "This is the location that the preprocessor will search for shaders when a #include directive is found.\n");
    char  **output_directory = c_program_flag_add_string("-shader_output_dir", "../build/", "This is the output location");
    bool32 *help             = c_program_flag_add_bool32("-help", false, "Displays the help message...\n");
    if(argc > 1)
    {
        c_program_flag_parse_args(argc, argv);
        if(*help == true)
        {
            c_program_flag_print_flag_list();
            return(0);
        }
    }
    
    file_manager_t file_manager = {};
    file_manager.output_directory = STR(*output_directory);
    file_manager.shader_directory = STR(*shader_directory);
    c_hash_table_init(&file_manager.loaded_files, 2048);

    visit_file_data_t visit_info = c_directory_create_visit_data(shader_file_callback, true, &file_manager);
    c_directory_visit(STR(*shader_directory), &visit_info);
    c_threadpool_flush_work_orders(&global_context->main_threadpool);

    return(0);
}
