/* ========================================================================
   $File: slang_reflector.cpp $
   $Date: April 21 2026 01:56 am $
   $Revision: $
   $Creator: Justin Lewis $
   ======================================================================== */
#include <c_types.h>
#include <c_base.h>
#include <c_synchronization.h>

#define DYNARRAY_IMPLEMENTATION 
#define HASH_TABLE_IMPLEMENTATION
#define PROGRAM_FLAG_HANDLER_IMPLEMENTATION

#include <c_hash_table.h>
#include <c_dynarray.h>
#include <c_program_flag_handler.h>

#include <c_global_context.cpp>
#include <c_file_api.cpp>
#include <p_platform_data.cpp>
#include <c_memory_arena.cpp>
#include <c_zone_allocator.cpp>
#include <c_string.cpp>
#include <c_threadpool.cpp>
#include <c_tokenizer.cpp>

constexpr u32 MAX_INCLUDED_FILES = 100;

struct slang_reflector_module_t
{
    tokenizer_t      tokenizer; 
    memory_arena_t   file_arena;
    string_builder_t new_file_builder;
    string_t         source_file;

    u64             *included_file_IDs;
    u32              included_file_count;
};

struct file_manager_t
{
    ticket_mutex_t         mutex;
    HashTable_t(string_t)  loaded_files;

    string_t               shader_directory;
    string_t               output_directory;
    string_t               generated_c_files_output_directory;
};

// NOTE(Sleepster): Thread local 
thread_static memory_arena_t thread_arena;

internal_api string_t 
remove_shader_structure_attributes(string_t *shader_data)
{
    tokenizer_t line_tokenizer = {*shader_data};

    string_builder_t transient_builder = {};
    c_string_builder_init(&transient_builder, KB(50));

    while(line_tokenizer.data.count > 0)
    {
        string_t current_line = c_tokenizer_eat_lines(&global_context->temporary_arena, &line_tokenizer, 1);
        bool8 attribute_found = false;

        tokenizer_t line = {current_line};
        while(line.data.count > 0)
        {
            token_data_t token = c_tokenizer_get_next_token(&line);
            switch(token.type)
            {
                case TT_OpenBracket:
                {
                    token_data_t test_token = c_tokenizer_peek_token(&line);
                    if(c_string_compare(test_token.string, STR("MakeHeaderType")) ||
                       c_string_compare(test_token.string, STR("Align")))
                    {
                        attribute_found = true;
                    }
                }break;
            }
        }

        if(!attribute_found)
        {
            c_string_builder_append_data(&transient_builder, current_line);
            c_string_builder_append_data(&transient_builder, STR("\n"));
        }
        else
        {
            c_string_builder_append_data(&transient_builder, STR("\n"));
        }
    }

    string_t result = c_string_builder_get_current_string(&transient_builder);
    return(result);
}

VISIT_FILES(shader_file_callback)
{
    file_manager_t *file_manager = (file_manager_t*)user_data;

    string_t fullname = visit_file_data->fullname;
    string_t filename = visit_file_data->filename;
    string_t file_ext = c_string_get_file_ext_from_path(filename);

    // NOTE(Sleepster): If we find a .slang file... we will add their includes appropriately. 
    if(c_string_compare(file_ext, STR(".slang")) || 
       c_string_compare(file_ext, STR(".slm")))
    {
        c_threadpool_push_work_order(&global_context->main_threadpool, [file_manager, filename, fullname]() {
            if(thread_arena.is_initialized == false)
            {
                thread_arena = c_arena_create(MB(20));
            }

            string_t *file_data = c_hash_table_get_value_ptr(&file_manager->loaded_files, filename);
            if(file_data->count == 0)
            {
                *file_data = c_file_read_entirety(fullname);
            }

            slang_reflector_module_t *module = c_arena_bootstrap_allocate_struct(slang_reflector_module_t, file_arena, MB(1));
            module->tokenizer   = tokenizer_t{*file_data};
            module->source_file = *file_data;
            module->included_file_IDs = c_arena_push_array(&module->file_arena, u64, MAX_INCLUDED_FILES);

            c_string_builder_init(&module->new_file_builder, MB(5));
            c_string_builder_append_data(&module->new_file_builder, STR("// THIS FILE IS AUTO GENERATED BY THE SLANG REFLECTOR...\n// DO NOT EDIT!!!!!\n\n"));

            tokenizer_t *tokenizer = &module->tokenizer;
            while(tokenizer->data.count > 0)
            {
                token_data_t token = c_tokenizer_get_next_token(tokenizer);
                switch(token.type)
                {
                    case TT_HashTag:
                    {
                        token_data_t preprocessor_token = c_tokenizer_get_next_token(tokenizer);
                        if(preprocessor_token.type == TT_Identifier)
                        {
                            // NOTE(Sleepster): Eat the "<" character so we can get the filename
                            c_tokenizer_get_next_token(tokenizer);
                            if(c_string_compare(preprocessor_token.string, STR("include")))
                            {
                                u64 ticket = c_ticket_mutex_take_ticket(&file_manager->mutex);
                                c_ticket_mutex_wait(&file_manager->mutex, ticket);

                                token_data_t included_filename_token = c_tokenizer_get_next_token(tokenizer);
                                string_t included_filename = c_string_concat(&thread_arena, file_manager->shader_directory, STR("/"));
                                         included_filename = c_string_concat(&thread_arena, included_filename, c_string_make_copy(&thread_arena, included_filename_token.string));

                                // NOTE(Sleepster): Eat the ">" character... 
                                c_tokenizer_get_next_token(tokenizer);

                                u64 ID  = c_fnv_hash_value(included_filename.data, included_filename.count);
                                    ID %= file_manager->loaded_files.header.max_entries;
                                string_t *included_file = file_manager->loaded_files.data + ID;

                                string_t working_filedata = *included_file;
                                if(included_file->count == 0)
                                {
                                   *included_file = c_file_read_entirety(included_filename);
                                }
                                c_ticket_mutex_advance_ticket(&file_manager->mutex);
                                working_filedata = remove_shader_structure_attributes(included_file);

                                bool8 found = false;

                                // TODO(Sleepster): Array find... 
                                for(u32 index = 0;
                                    index < module->included_file_count;
                                    ++index)
                                {
                                    u64 found_ID = module->included_file_IDs[index];
                                    if(found_ID == ID)
                                    {
                                        found = true;
                                        break;
                                    }
                                }

                                if(!found)
                                {
                                    module->included_file_IDs[module->included_file_count++] = ID;
                                    c_string_builder_append_data(&module->new_file_builder,  STR("// FROM INCLUDED FILE: "));
                                    c_string_builder_append_data(&module->new_file_builder,  included_filename);
                                    c_string_builder_append_data(&module->new_file_builder,  STR("\n"));
                                    c_string_builder_append_data(&module->new_file_builder,  STR("#line 1 \""));
                                    c_string_builder_append_data(&module->new_file_builder,  included_filename);
                                    c_string_builder_append_data(&module->new_file_builder,  STR("\"\n"));
                                    c_string_builder_append_data(&module->new_file_builder,  working_filedata);
                                    c_string_builder_append_data(&module->new_file_builder,  STR("// END OF INCLUDED FILE\n"));

                                    module->source_file = tokenizer->data;
                                }
                            }
                        }
                    }break;
                }
            }

            c_string_builder_append_data(&module->new_file_builder, STR("#line 1 \""));
            c_string_builder_append_data(&module->new_file_builder, filename);
            c_string_builder_append_data(&module->new_file_builder, STR("\"\n"));
            c_string_builder_append_data(&module->new_file_builder, module->source_file);

            u64 ticket = c_ticket_mutex_take_ticket(&file_manager->mutex);
            c_ticket_mutex_wait(&file_manager->mutex, ticket);

            string_t output_file = c_string_concat(&thread_arena, file_manager->output_directory, filename);

            c_ticket_mutex_advance_ticket(&file_manager->mutex);

            file_t new_file = c_file_open(output_file, true);
            c_string_builder_dump_to_file(&new_file, &module->new_file_builder);
            
            log_info("Wrote file: '%.*s' out...\n", output_file.count, C_STR(output_file));
        }, null);
    }
    else if(c_string_compare(file_ext, STR(".slh")))
    {
        // NOTE(Sleepster): We could just use a normal "&" here but I just don't care and this is more explicit 
        c_threadpool_push_work_order(&global_context->main_threadpool, [file_manager, filename, fullname]() {
            if(thread_arena.is_initialized == false)
            {
                thread_arena = c_arena_create(MB(20));
            }

            string_t *file_data = c_hash_table_get_value_ptr(&file_manager->loaded_files, filename);
            if(file_data->count == 0)
            {
                *file_data = c_file_read_entirety(fullname);
            }

            string_builder_t header_builder = {};
            c_string_builder_init(&header_builder, MB(5));

            string_t define_filename = c_string_to_upper(filename);
            s32 file_ext_start = c_string_find_first_char_from_right(define_filename, '.');
            if(file_ext_start != -1)
            {
                define_filename.data[file_ext_start] = '_';
            }

            c_string_builder_sprintf(&header_builder, 
                                     "// THIS FILE IS AUTOGENERATED FROM FILE: '%.*s'...\n// DO NOT EDIT!!!!!\n", 
                                     filename.count, C_STR(filename));
            c_string_builder_sprintf(&header_builder, "#ifndef %.*s\n", define_filename.count, define_filename.data);
            c_string_builder_sprintf(&header_builder, "#define %.*s\n", define_filename.count, define_filename.data);
            c_string_builder_append_data(&header_builder, STR(R"(
#include <c_math.h>
#include <c_types.h>

typedef vec2_t float2;
typedef vec3_t float3;
typedef vec4_t float4;

typedef mat2_t float2x2;
typedef mat3_t float3x3;
typedef mat4_t float4x4;

typedef uint   u32;
typedef int    s32;
typedef float  float32;

)"));

            // TODO(Sleepster): For here, the metaprogram would benefit from having a public interface to interact with all the
            // datatypes and such to just call something like "parse_C_structure()" and have it return to you all the information you need 
            // about it said structure... but unfortunately the metaprogram was not built with this in mind.
            s32 current_alignment = 0;

            tokenizer_t tokenizer = {*file_data};
            while(tokenizer.data.count > 0)
            {
                token_data_t token = c_tokenizer_get_next_token(&tokenizer);
                switch(token.type)
                {
                    case TT_OpenBracket:
                    {
                        // NOTE(Sleepster): Get the tag... 
                        token_data_t tag_token = c_tokenizer_get_next_token(&tokenizer);
                        Expect(tag_token.type == TT_Identifier, "The item following the open bracket must be an identifier...\n");

                        if(c_string_compare(tag_token.string, STR("MakeHeaderType")))
                        {
                            // NOTE(Sleepster): Eat the closing bracket... 
                            c_tokenizer_get_next_token(&tokenizer);
                            token_data_t type_token = c_tokenizer_get_next_token(&tokenizer);
                            Expect(type_token.type == TT_Identifier, "Token: '%.*s' is not an identifier...\nYou cannot have another attribute after [MakeHeaderType]...\n",
                                   type_token.string.count, C_STR(type_token.string));

                            if(c_string_compare(type_token.string, STR("struct")))
                            {
                                c_string_builder_append_data(&header_builder, STR("struct "));
                                if(current_alignment > 0)
                                {
                                    c_string_builder_sprintf(&header_builder, "alignas(%u) ", current_alignment);
                                }

                                // NOTE(Sleepster): Get the name of the structure
                                token_data_t name_token = c_tokenizer_get_next_token(&tokenizer);
                                Expect(name_token.type == TT_Identifier, "The token after the 'struct' definition MUST be a name...\n");

                                c_string_builder_sprintf(&header_builder, 
                                                         "%.*s {\n\t",
                                                          name_token.string.count, C_STR(name_token.string));

                                // NOTE(Sleepster): Read the members and their types 
                                token_data_t token = c_tokenizer_get_next_token(&tokenizer);
                                while(token.type != TT_ClosingBrace)
                                {
                                    if(token.type == TT_Identifier)
                                    {
                                        c_string_builder_sprintf(&header_builder, 
                                                                 "%.*s ", 
                                                                 token.string.count, C_STR(token.string));
                                    }
                                    if(token.type == TT_Colon)
                                    {
                                        c_tokenizer_get_next_token(&tokenizer);
                                    }
                                    if(token.type == TT_Semicolon)
                                    {
                                        header_builder.current_buffer->bytes_used -= 1;
                                        c_string_builder_append_data(&header_builder, STR(";\n\t"));
                                    }

                                    token = c_tokenizer_get_next_token(&tokenizer);
                                }

                                current_alignment = 0;
                                header_builder.current_buffer->bytes_used -= 1;
                                c_string_builder_append_data(&header_builder, STR("};\n"));
                            }
                            else if(c_string_compare(type_token.string, STR("enum")))
                            {
                                token_data_t name_token = c_tokenizer_get_next_token(&tokenizer);
                                Expect(name_token.type == TT_Identifier, "The token after the 'enum' definition MUST be a name...\n");
                                // NOTE(Sleepster): Eat the open paren... 
                                c_tokenizer_get_next_token(&tokenizer);

                                c_string_builder_sprintf(&header_builder, "enum %.*s {\n\t", name_token.string.count, C_STR(name_token.string));
                                token_data_t token = c_tokenizer_get_next_token(&tokenizer);

                                u32 current_enum_value = INVALID_ID;
                                while(token.type != TT_ClosingBrace)
                                {
                                    if(token.type == TT_Identifier)
                                    {
                                        c_string_builder_sprintf(&header_builder, 
                                                                 "%.*s ", 
                                                                 token.string.count, C_STR(token.string));
                                    }
                                    else if(token.type == TT_Equals)
                                    {
                                        c_string_builder_append_data(&header_builder, token.string);
                                        token_data_t number_token = c_tokenizer_get_next_token(&tokenizer);
                                        if(number_token.type == TT_Number)
                                        {
                                            token_data_t peek_token = c_tokenizer_peek_token(&tokenizer);
                                            Expect(peek_token.type == TT_Comma, "Failure to parse number token: '%.*s'... If you wanted to use a bitshifted value, please use (1 << x) notation...\n",
                                                   peek_token.string.count, C_STR(peek_token.string));

                                            current_enum_value = c_string_read_uint(number_token.string);
                                        }
                                        else if(number_token.type == TT_OpeningParen)
                                        {
                                            c_string_builder_append_data(&header_builder, STR(" "));
                                            c_string_builder_append_data(&header_builder, STR("("));
                                            number_token = c_tokenizer_get_next_token(&tokenizer);
                                            Expect(number_token.type == TT_Number, "Failure... Token: '%.*s' is not of type number... You must have a number in the parenthesis...\n",
                                                   number_token.string.count, C_STR(number_token.string));

                                            c_string_builder_append_data(&header_builder, number_token.string);

                                            // NOTE(Sleepster): This will just stright up append these tokens and that's fine since if we find something bad... we just exit... 
                                            number_token = c_tokenizer_get_next_token(&tokenizer);
                                            if(number_token.type == TT_OpenAngleBracket)
                                            {
                                                c_string_builder_append_data(&header_builder, STR(" "));
                                                c_string_builder_append_data(&header_builder, number_token.string);

                                                number_token = c_tokenizer_get_next_token(&tokenizer);
                                                Expect(number_token.type == TT_OpenAngleBracket, "Failure... Token: '%.*s' is not of type open angle bracket... You must have a pair of open angle brackets...\n",
                                                       number_token.string.count, C_STR(number_token.string));

                                                c_string_builder_append_data(&header_builder, number_token.string);
                                                c_string_builder_append_data(&header_builder, STR(" "));

                                                number_token = c_tokenizer_get_next_token(&tokenizer);
                                                Expect(number_token.type == TT_Number, "Failure... Token: '%.*s' is not of type number...\n",
                                                       number_token.string.count, C_STR(number_token.string));
                                                c_string_builder_append_data(&header_builder, number_token.string);
                                                number_token = c_tokenizer_get_next_token(&tokenizer);
                                                c_string_builder_append_data(&header_builder, STR(")"));

                                                Expect(number_token.type == TT_ClosingParen, "Failure... Token: '%.*s' is not of type Close Paren...\n",
                                                       number_token.string.count, C_STR(number_token.string));
                                                c_string_builder_append_data(&header_builder, number_token.string);

                                            }
                                            else if(number_token.type == TT_ClosingParen)
                                            {
                                                c_string_builder_append_data(&header_builder, STR(")"));
                                                current_enum_value = c_string_read_uint(number_token.string);
                                            }
                                            else
                                            {
                                                Expect(false, "Not sure what you're trying to do here... but token: '%.*s' is invalid after the '=' sign...\n",
                                                       number_token.string.count, C_STR(number_token.string));
                                            }
                                        }
                                        else
                                        {
                                            Expect(false, "Failure to parse item: '%.*s' after the equals sign in the enumeration: '%.*s'... Only a number or (1 << x) notation is allowed after the equals...\n",
                                                   number_token.string.count, C_STR(number_token.string));
                                        }
                                    }
                                    else if(token.type == TT_Comma)
                                    {
                                        if(current_enum_value != INVALID_ID)
                                        {
                                            c_string_builder_sprintf(&header_builder, " %lu", current_enum_value);
                                        }
                                        header_builder.current_buffer->bytes_used -= 1;
                                        c_string_builder_append_data(&header_builder, STR(",\n\t"));
                                    }
                                    else
                                    {
                                        log_error("Failure... Token: '%.*s' is invalid in this location... Found when parsing enum...\n",
                                                  token.string.count, C_STR(token.string));
                                    }

                                    token = c_tokenizer_get_next_token(&tokenizer);
                                }

                                header_builder.current_buffer->bytes_used -= 1;
                                c_string_builder_append_data(&header_builder, STR("};\n"));
                            }
                        }
                        else if(c_string_compare(tag_token.string, STR("Align")))
                        {
                            // NOTE(Sleepster): Eat open paren 
                            token_data_t alignment = c_tokenizer_get_next_token(&tokenizer);
                            Expect(alignment.type == TT_OpeningParen, "This should be an open parenthesis... Usage is like so:\n[Align(16)]\n");

                            alignment = c_tokenizer_get_next_token(&tokenizer);
                            Expect(alignment.type == TT_Number, "This should be a valid number... Usage is like so:\n[Align(16)]\n");

                            current_alignment = c_string_read_int(alignment.string);
                            c_tokenizer_eat_lines(&thread_arena, &tokenizer, 1);
                        }
                    }break;
                }
            }

            c_string_builder_sprintf(&header_builder, "#endif // %.*s\n", define_filename.count, C_STR(define_filename));
            
            string_t new_filename = filename;
            new_filename.count -= 4;

            u64 ticket = c_ticket_mutex_take_ticket(&file_manager->mutex);
            c_ticket_mutex_wait(&file_manager->mutex, ticket);

            new_filename = c_string_concat(&thread_arena, STR("GENERATED_"), new_filename);
            new_filename = c_string_concat(&thread_arena, file_manager->generated_c_files_output_directory, new_filename);
            string_t output_file = c_string_concat(&thread_arena, 
                                                   new_filename, 
                                                   STR(".h"));

            c_ticket_mutex_advance_ticket(&file_manager->mutex);

            file_t new_meta_file = c_file_open(output_file, true);
            c_string_builder_dump_to_file(&new_meta_file, &header_builder);
            log_info("Generated C header file: '%.*s' for .slh file: '%.*s'...\n",
                     output_file.count, C_STR(output_file),
                     filename.count,    C_STR(filename));
        }, null);
    }
}

int
main(int argc, char **argv)
{
    c_global_context_init();

    u32 thread_count = sys_get_thread_count();
    c_threadpool_init(&global_context->main_threadpool, thread_count, MB(1), true);

    char  **shader_input_directory      = c_program_flag_add_string("-shader_input_path", "shaders/", "This is the location that the preprocessor will search for shaders when a #include directive is found.\n");
    char  **shader_output_directory     = c_program_flag_add_string("-shader_output_dir", "../build/", "This is the output location for the newly generated .slang files");
    char  **metagen_c_header_output_dir = c_program_flag_add_string("-metagen_c_header_output_dir", "meta/", "This is the output location for the generated .h files");

    bool32 *help  = c_program_flag_add_bool32("-help", false, "Displays the help message...\n");
    if(argc > 1)
    {
        c_program_flag_parse_args(argc, argv);
        if(*help == true)
        {
            c_program_flag_print_flag_list();
            return(0);
        }
    }
    
    file_manager_t file_manager   = {};
    file_manager.shader_directory = STR(*shader_input_directory);
    file_manager.output_directory = STR(*shader_output_directory);
    file_manager.generated_c_files_output_directory = STR(*metagen_c_header_output_dir);
    c_hash_table_init(&file_manager.loaded_files, 2048);

    visit_file_data_t visit_info = c_directory_create_visit_data(shader_file_callback, true, &file_manager);
    c_directory_visit(STR(*shader_input_directory), &visit_info);
    c_threadpool_flush_work_orders(&global_context->main_threadpool);

    return(0);
}
