// THIS FILE IS GENERATED BY THE ATHENA REFLECTOR
// DO NOT EDIT!!!!!!

#if !defined(ATHENA_GENERATED_FILE_H)
#define ATHENA_GENERATED_FILE_H

#define ATHENA_RTTI_COMPLETE_TYPE_LIST(X) \
	X(unsigned int, &DEFAULT_typedata_unsigned_int) \
	X(unsigned char, &DEFAULT_typedata_unsigned_char) \
	X(short, &DEFAULT_typedata_short) \
	X(long, &DEFAULT_typedata_long) \
	X(int, &DEFAULT_typedata_int) \
	X(char, &DEFAULT_typedata_char) \
	X(float, &DEFAULT_typedata_float) \
	X(double, &DEFAULT_typedata_double) \
	X(void, &DEFAULT_typedata_void) \
	X(bool, &DEFAULT_typedata_bool) \
	X(int8_t, &DEFAULT_typedata_int8_t) \
	X(int16_t, &DEFAULT_typedata_int16_t) \
	X(int32_t, &DEFAULT_typedata_int32_t) \
	X(int64_t, &DEFAULT_typedata_int64_t) \
	X(uint8_t, &DEFAULT_typedata_uint8_t) \
	X(uint16_t, &DEFAULT_typedata_uint16_t) \
	X(uint32_t, &DEFAULT_typedata_uint32_t) \
	X(uint64_t, &DEFAULT_typedata_uint64_t) \
	X(size_t, &DEFAULT_typedata_size_t) \
	X(test_structure, &DEFAULT_typedata_structure_test_structure.type_info) \


#include <string.h>
#include <stddef.h>
#ifndef ATHENA_H
#error "You must include athena.h before this file..."
#endif

CODE_GEN_IGNORE_FILE

extern const type_info_t *const athena_type_information_array[];
struct type_info_struct_test_structure {
	const type_info_t  type_info;
	const unsigned int member_count;
	const type_info_member_t *member_pointer;
	union {
		const type_info_member_t member_array[4];
		struct {
			const type_info_member_t apples;
			const type_info_member_t oranges;
			const type_info_member_t bananas;
			const type_info_member_t apples_test_func;
		}members;
	};
};

struct type_info_procedure_attribute_test_function {
	const type_info_t  type_info;
	const unsigned int argument_count;
	const type_info_t *return_type;
	const type_info_member_t *argument_pointer;
	union {
		type_info_member_t argument_array[1];
		struct {
			const type_info_member_t apples;
		}arguments;
	};
};

struct type_info_procedure_main {
	const type_info_t  type_info;
	const unsigned int argument_count;
	const type_info_t *return_type;
	const type_info_member_t *argument_pointer;
	union {
		type_info_member_t argument_array[2];
		struct {
			const type_info_member_t argc;
			const type_info_member_t argv;
		}arguments;
	};
};

struct type_info_procedure_apples_test_func {
	const type_info_t  type_info;
	const unsigned int argument_count;
	const type_info_t *return_type;
	const type_info_member_t *argument_pointer;
	union {
		type_info_member_t argument_array[1];
		struct {
			const type_info_member_t name;
		}arguments;
	};
};

extern const type_info_t DEFAULT_typedata_unsigned_int;
extern const type_info_t DEFAULT_typedata_unsigned_char;
extern const type_info_t DEFAULT_typedata_short;
extern const type_info_t DEFAULT_typedata_long;
extern const type_info_t DEFAULT_typedata_int;
extern const type_info_t DEFAULT_typedata_char;
extern const type_info_t DEFAULT_typedata_float;
extern const type_info_t DEFAULT_typedata_double;
extern const type_info_t DEFAULT_typedata_bool;
extern const type_info_t DEFAULT_typedata_int8_t;
extern const type_info_t DEFAULT_typedata_int16_t;
extern const type_info_t DEFAULT_typedata_int32_t;
extern const type_info_t DEFAULT_typedata_int64_t;
extern const type_info_t DEFAULT_typedata_uint8_t;
extern const type_info_t DEFAULT_typedata_uint16_t;
extern const type_info_t DEFAULT_typedata_uint32_t;
extern const type_info_t DEFAULT_typedata_uint64_t;
extern const type_info_t DEFAULT_typedata_size_t;
extern const type_info_struct_test_structure DEFAULT_typedata_structure_test_structure;
extern const type_info_procedure_attribute_test_function DEFAULT_typedata_procedure_attribute_test_function;
extern const type_info_procedure_main DEFAULT_typedata_procedure_main;
extern const type_info_procedure_apples_test_func DEFAULT_typedata_procedure_apples_test_func;

constexpr type_info_t DEFAULT_typedata_unsigned_int = {
	.type_name = "unsigned int",
	.metatype  = ATHENA_METATYPE_PRIMITIVE,
	.size = athena_internal::safe_sizeof<unsigned int>(),
};
constexpr type_info_t DEFAULT_typedata_unsigned_char = {
	.type_name = "unsigned char",
	.metatype  = ATHENA_METATYPE_PRIMITIVE,
	.size = athena_internal::safe_sizeof<unsigned char>(),
};
constexpr type_info_t DEFAULT_typedata_short = {
	.type_name = "short",
	.metatype  = ATHENA_METATYPE_PRIMITIVE,
	.size = athena_internal::safe_sizeof<short>(),
};
constexpr type_info_t DEFAULT_typedata_long = {
	.type_name = "long",
	.metatype  = ATHENA_METATYPE_PRIMITIVE,
	.size = athena_internal::safe_sizeof<long>(),
};
constexpr type_info_t DEFAULT_typedata_int = {
	.type_name = "int",
	.metatype  = ATHENA_METATYPE_PRIMITIVE,
	.size = athena_internal::safe_sizeof<int>(),
};
constexpr type_info_t DEFAULT_typedata_char = {
	.type_name = "char",
	.metatype  = ATHENA_METATYPE_PRIMITIVE,
	.size = athena_internal::safe_sizeof<char>(),
};
constexpr type_info_t DEFAULT_typedata_float = {
	.type_name = "float",
	.metatype  = ATHENA_METATYPE_PRIMITIVE,
	.size = athena_internal::safe_sizeof<float>(),
};
constexpr type_info_t DEFAULT_typedata_double = {
	.type_name = "double",
	.metatype  = ATHENA_METATYPE_PRIMITIVE,
	.size = athena_internal::safe_sizeof<double>(),
};
constexpr type_info_t DEFAULT_typedata_void = {
	.type_name = "void",
	.metatype  = ATHENA_METATYPE_PRIMITIVE,
};
constexpr type_info_t DEFAULT_typedata_bool = {
	.type_name = "bool",
	.metatype  = ATHENA_METATYPE_PRIMITIVE,
	.size = athena_internal::safe_sizeof<bool>(),
};
constexpr type_info_t DEFAULT_typedata_int8_t = {
	.type_name = "int8_t",
	.metatype  = ATHENA_METATYPE_PRIMITIVE,
	.size = athena_internal::safe_sizeof<int8_t>(),
};
constexpr type_info_t DEFAULT_typedata_int16_t = {
	.type_name = "int16_t",
	.metatype  = ATHENA_METATYPE_PRIMITIVE,
	.size = athena_internal::safe_sizeof<int16_t>(),
};
constexpr type_info_t DEFAULT_typedata_int32_t = {
	.type_name = "int32_t",
	.metatype  = ATHENA_METATYPE_PRIMITIVE,
	.size = athena_internal::safe_sizeof<int32_t>(),
};
constexpr type_info_t DEFAULT_typedata_int64_t = {
	.type_name = "int64_t",
	.metatype  = ATHENA_METATYPE_PRIMITIVE,
	.size = athena_internal::safe_sizeof<int64_t>(),
};
constexpr type_info_t DEFAULT_typedata_uint8_t = {
	.type_name = "uint8_t",
	.metatype  = ATHENA_METATYPE_PRIMITIVE,
	.size = athena_internal::safe_sizeof<uint8_t>(),
};
constexpr type_info_t DEFAULT_typedata_uint16_t = {
	.type_name = "uint16_t",
	.metatype  = ATHENA_METATYPE_PRIMITIVE,
	.size = athena_internal::safe_sizeof<uint16_t>(),
};
constexpr type_info_t DEFAULT_typedata_uint32_t = {
	.type_name = "uint32_t",
	.metatype  = ATHENA_METATYPE_PRIMITIVE,
	.size = athena_internal::safe_sizeof<uint32_t>(),
};
constexpr type_info_t DEFAULT_typedata_uint64_t = {
	.type_name = "uint64_t",
	.metatype  = ATHENA_METATYPE_PRIMITIVE,
	.size = athena_internal::safe_sizeof<uint64_t>(),
};
constexpr type_info_t DEFAULT_typedata_size_t = {
	.type_name = "size_t",
	.metatype  = ATHENA_METATYPE_PRIMITIVE,
	.size = athena_internal::safe_sizeof<size_t>(),
};
constexpr type_info_struct_test_structure DEFAULT_typedata_structure_test_structure = {
	.type_info = {
		.type_name = "test_structure",
		.metatype  = ATHENA_METATYPE_STRUCT,
		.size = athena_internal::safe_sizeof<test_structure>(),
	},
	.member_count   = 4,
	.member_pointer = DEFAULT_typedata_structure_test_structure.member_array,
	.members = {
		.apples = {
			.type_info     = &DEFAULT_typedata_int,
			.member_name   = "apples",
			.parent        = &DEFAULT_typedata_structure_test_structure.type_info,
			.offset        = offsetof(test_structure, apples),
			.flags         = 0,
			.pointer_depth = 0,
			.value = {
				.type = 3,
				.u64 = 4,
			},
		},
		.oranges = {
			.type_info     = &DEFAULT_typedata_int,
			.member_name   = "oranges",
			.parent        = &DEFAULT_typedata_structure_test_structure.type_info,
			.offset        = offsetof(test_structure, oranges),
			.flags         = 0,
			.pointer_depth = 0,
		},
		.bananas = {
			.type_info     = &DEFAULT_typedata_int,
			.member_name   = "bananas",
			.parent        = &DEFAULT_typedata_structure_test_structure.type_info,
			.offset        = offsetof(test_structure, bananas),
			.flags         = 0,
			.pointer_depth = 0,
		},
		.apples_test_func = {
			.type_info     = &DEFAULT_typedata_procedure_apples_test_func.type_info,
			.member_name   = "apples_test_func",
			.parent        = &DEFAULT_typedata_structure_test_structure.type_info,
			.flags         = 1024,
			.pointer_depth = 0,
		},
	},
};

constexpr type_info_procedure_attribute_test_function DEFAULT_typedata_procedure_attribute_test_function = {
	.type_info = {
		.type_name = "attribute_test_function",
		.metatype  = ATHENA_METATYPE_PROCEDURE,
	},
	.argument_count = 1,
	.return_type    = &DEFAULT_typedata_void,
	.argument_pointer = DEFAULT_typedata_procedure_attribute_test_function.argument_array,
	.arguments = {
		.apples = {
			.type_info     = &DEFAULT_typedata_int,
			.member_name   = "apples",
			.parent        = &DEFAULT_typedata_procedure_attribute_test_function.type_info,
			.flags         = 0,
			.pointer_depth = 0,
			.value = {
				.type = 3,
				.u64 = 4,
			},
		},
	},
};
constexpr type_info_procedure_main DEFAULT_typedata_procedure_main = {
	.type_info = {
		.type_name = "main",
		.metatype  = ATHENA_METATYPE_PROCEDURE,
	},
	.argument_count = 2,
	.return_type    = &DEFAULT_typedata_int,
	.argument_pointer = DEFAULT_typedata_procedure_main.argument_array,
	.arguments = {
		.argc = {
			.type_info     = &DEFAULT_typedata_int,
			.member_name   = "argc",
			.parent        = &DEFAULT_typedata_procedure_main.type_info,
			.flags         = 0,
			.pointer_depth = 0,
		},
		.argv = {
			.type_info     = &DEFAULT_typedata_char,
			.member_name   = "argv",
			.parent        = &DEFAULT_typedata_procedure_main.type_info,
			.flags         = 2,
			.pointer_depth = 2,
		},
	},
};
constexpr type_info_procedure_apples_test_func DEFAULT_typedata_procedure_apples_test_func = {
	.type_info = {
		.type_name = "apples_test_func",
		.metatype  = ATHENA_METATYPE_PROCEDURE,
	},
	.argument_count = 1,
	.return_type    = &DEFAULT_typedata_char,
	.argument_pointer = DEFAULT_typedata_procedure_apples_test_func.argument_array,
	.arguments = {
		.name = {
			.type_info     = &DEFAULT_typedata_char,
			.member_name   = "name",
			.parent        = &DEFAULT_typedata_procedure_apples_test_func.type_info,
			.flags         = 2,
			.pointer_depth = 1,
			.value = {
				.type = 7,
				.string = "test",
			},
		},
	},
};
constexpr const type_info_t *const athena_type_information_array[] = {
	&DEFAULT_typedata_unsigned_int,
	&DEFAULT_typedata_unsigned_char,
	&DEFAULT_typedata_short,
	&DEFAULT_typedata_long,
	&DEFAULT_typedata_int,
	&DEFAULT_typedata_char,
	&DEFAULT_typedata_float,
	&DEFAULT_typedata_double,
	&DEFAULT_typedata_void,
	&DEFAULT_typedata_bool,
	&DEFAULT_typedata_int8_t,
	&DEFAULT_typedata_int16_t,
	&DEFAULT_typedata_int32_t,
	&DEFAULT_typedata_int64_t,
	&DEFAULT_typedata_uint8_t,
	&DEFAULT_typedata_uint16_t,
	&DEFAULT_typedata_uint32_t,
	&DEFAULT_typedata_uint64_t,
	&DEFAULT_typedata_size_t,
	&DEFAULT_typedata_structure_test_structure.type_info,
	&DEFAULT_typedata_procedure_attribute_test_function.type_info,
	&DEFAULT_typedata_procedure_main.type_info,
	&DEFAULT_typedata_procedure_apples_test_func.type_info,
};

namespace Athena {
namespace MemberLists {
enum class test_structure {
	apples,
	oranges,
	bananas,
	apples_test_func,
}; // test_structure
}; // namespace MemberLists
namespace ArgumentLists {
enum class attribute_test_function {
	apples,
}; // attribute_test_function
enum class main {
	argc,
	argv,
}; // main
enum class apples_test_func {
	name,
}; // apples_test_func
}; // namespace ArgumentLists
}; // namespace Athena

constexpr const type_info_t *ATTRIBUTE_member_func_array[] = {
	&DEFAULT_typedata_procedure_apples_test_func.type_info,
};
constexpr const type_info_t *ATTRIBUTE_generate_function_array[] = {
	&DEFAULT_typedata_procedure_attribute_test_function.type_info,
};
constexpr attribute_info_list_t complete_attribute_array[] = {
	{"member_func", ATTRIBUTE_member_func_array, ArrayCount(ATTRIBUTE_member_func_array)},
	{"generate_function", ATTRIBUTE_generate_function_array, ArrayCount(ATTRIBUTE_generate_function_array)},
};

ATHENA_API const type_info_t *type_info(unsigned long long type_id);
ATHENA_API const type_info_t *type_info(const char *string);

#ifdef C_STRING_H
ATHENA_API inline const type_info_t *type_info(string_t string);
#endif

// NOTE(Sleepster): STB style lib
#ifdef ATHENA_IMPLMENTATION 

#ifndef ArrayCount
#define ArrayCount(x) (sizeof(x) / sizeof((x[0])))
#endif

#include <type_traits>
namespace Athena {

ATHENA_API const type_info_t*
type_info(unsigned long long type_id)
{
    const type_info_t *result = (const type_info_t*)athena_type_information_array[type_id];
    return(result);
};

#ifdef C_STRING_H
ATHENA_API const type_info_t*
type_info(string_t string)
{
    const type_info_t *result = null;
    if(string.count > 0)
    {
        for(auto &element: athena_type_information_array)
        {
            if(c_string_compare(STR(element->type_name), string))
            {
                result = element;
                break;
            }
        }
    }

    return(result);
}

ATHENA_API const type_info_member_t*
get_member_info(const type_info_t *type_info, string_t member_name) 
{
    const type_info_member_t *result = null;

    if(member_name.count > 0)
    {
        const type_info_struct_t *structure_info = (const type_info_struct_t*)type_info;
        for(u32 member_index = 0;
            member_index < structure_info->member_count;
            ++member_index)
        {
            const type_info_member_t *member = &structure_info->members[member_index];
            if(c_string_compare(STR(member->member_name), member_name))
            {
                result = (const type_info_member_t*)(member);
                break;
            }
        }
    }

    return(result);
}
#endif

ATHENA_API const type_info_t*
type_info(const char *string)
{
    const type_info_t *result = nullptr;

    int string_length = strlen(string);
    if(string_length > 0)
    {
        for(unsigned int index = 0;
            index < ArrayCount(athena_type_information_array);
            ++index)
        {
            const type_info_t *element = athena_type_information_array[index];

            int element_length = strlen(element->type_name);
            if(string_length != element_length) continue;
            if(memcmp(element->type_name, string, element_length) == 0)
            {
                result = element;
                break;
            }
        }
    }

    return(result);
}

ATHENA_API const type_info_member_t*
get_member(const type_info_t *type_info, const char *member_name) 
{
    const type_info_member_t *result = nullptr;

    int name_length = strlen(member_name);
    if(name_length > 0)
    {
        const type_info_struct_t *structure_info = (const type_info_struct_t*)type_info;
        for(unsigned int member_index = 0;
            member_index < structure_info->member_count;
            ++member_index)
        {
            const type_info_member_t *member = structure_info->members + member_index;

            int member_length = strlen(member->member_name);
            if(member_length != name_length) continue;

            if(memcmp(member_name, member->member_name, member_length) == 0)
            {
                result = member;
                break;
            }
        }
    }

    return(result);
}

ATHENA_API const type_info_member_t*
get_member(const type_info_struct_t *type_info, const char *member_name) 
{
    const type_info_member_t *result = nullptr;

    int name_length = strlen(member_name);
    if(name_length > 0)
    {
        for(unsigned int member_index = 0;
            member_index < type_info->member_count;
            ++member_index)
        {
            const type_info_member_t *member = type_info->members + member_index;

            int member_length = strlen(member->member_name);
            if(member_length != name_length) continue;

            if(memcmp(member_name, member->member_name, member_length) == 0)
            {
                result = member;
                break;
            }
        }
    }

    return(result);
}

ATHENA_API const type_info_member_t*
get_argument(const type_info_t *info, const char *name)
{
    const type_info_member_t *result = nullptr;
    int name_length = strlen(name);
    if(name_length > 0)
    {
        const type_info_procedure_t *proc_info = Athena::as_procedure(info);
        for(unsigned int argument_index = 0;
            argument_index < proc_info->argument_count;
            ++argument_index)
        {
            const type_info_member_t *argument = proc_info->arguments + argument_index;

            int member_length = strlen(argument->member_name);
            if(member_length != name_length) continue;

            if(memcmp(name, argument->member_name, member_length) == 0)
            {
                result = argument;
                break;
            }
        }
    }

    return(result);
}

ATHENA_API const type_info_member_t*
get_argument(const type_info_procedure_t *info, const char *name)
{
    const type_info_member_t *result = nullptr;
    int name_length = strlen(name);
    if(name_length > 0)
    {
        for(unsigned int argument_index = 0;
            argument_index < info->argument_count;
            ++argument_index)
        {
            const type_info_member_t *argument = info->arguments + argument_index;

            int member_length = strlen(argument->member_name);
            if(member_length != name_length) continue;

            if(memcmp(name, argument->member_name, member_length) == 0)
            {
                result = argument;
                break;
            }
        }
    }

    return(result);
}

template <class T>
ATHENA_API const type_info_member_t*
get_member(const type_info_t *info, T index)
{
    const type_info_member_t *result = nullptr;

    Assert(info->metatype == ATHENA_METATYPE_STRUCT);
    const type_info_struct_t *struct_info = Athena::as_structure(info);

    const unsigned int true_index = (static_cast<const unsigned int>(index));
    if(true_index <= struct_info->member_count)
    {
        result = (struct_info->members + true_index);
    }

    return(result);
}

template <class T>
ATHENA_API const type_info_member_t*
get_member(const type_info_struct_t *info, T index)
{
    const type_info_member_t *result = nullptr;
    Assert(info->type_info.metatype == ATHENA_METATYPE_STRUCT);

    const unsigned int true_index = (static_cast<const unsigned int>(index));
    if(true_index <= info->member_count)
    {
        result = (info->members + true_index);
    }

    return(result);
}

template <class T>
ATHENA_API const type_info_member_t*
get_argument(const type_info_t *info, T index)
{
    const type_info_member_t *result = nullptr;
    Assert(info->metatype == ATHENA_METATYPE_PROCEDURE);

    const type_info_procedure_t *proc = Athena::as_procedure(info);

    const unsigned int true_index = (static_cast<const unsigned int>(index));
    if(true_index <= proc->argument_count)
    {
        result = (proc->arguments + true_index);
    }

    return(result);
}

template <class T>
ATHENA_API const type_info_member_t*
get_argument(const type_info_procedure_t *info, T index)
{
    const type_info_member_t *result = nullptr;
    Assert(info->type_info.metatype == ATHENA_METATYPE_PROCEDURE);

    const unsigned int true_index = (static_cast<const unsigned int>(index));
    if(true_index <= info->argument_count)
    {
        result = (info->arguments + true_index);
    }

    return(result);
}

ATHENA_API const type_info_struct_t*
get_struct_info_from_member(const type_info_t *info)
{
    const type_info_struct_t *result = nullptr;
    const type_info_member_t *member = (const type_info_member_t*)info;
    if(member->parent)
    {
        result = (type_info_struct_t*)member->parent;
    }

    return(result);
}

ATHENA_API const type_info_struct_t*
get_struct_info_from_member(const type_info_member_t *member)
{
    const type_info_struct_t *result = nullptr;
    if(member->parent)
    {
        result = (type_info_struct_t*)member->parent;
    }

    return(result);
}

ATHENA_API const type_info_procedure_t*
as_procedure(const type_info_t *info)
{
    Assert(info->metatype == ATHENA_METATYPE_PROCEDURE);
    return((const type_info_procedure_t *)info);
}

ATHENA_API const type_info_procedure_t*
as_procedure(const type_info_member_t *info)
{
    Assert(info->type_info->metatype == ATHENA_METATYPE_PROCEDURE);
    return((const type_info_procedure_t *)info->type_info);
}

ATHENA_API const type_info_struct_t*
as_structure(const type_info_member_t *info)
{
    Assert(info->type_info->metatype == ATHENA_METATYPE_STRUCT);
    return((const type_info_struct_t *)info->type_info);
}

ATHENA_API const type_info_struct_t*
as_structure(const type_info_t *info)
{
    Assert(info->metatype == ATHENA_METATYPE_STRUCT);
    return((const type_info_struct_t *)info);
}

// NOTE(Sleepster): Templates
template<typename T> constexpr const type_info_t* type_info();

#define X(cpp_type, structure) \
    std::is_same<T, cpp_type>::value ? (const type_info_t*)(structure) :

template<typename T>
constexpr const type_info_t* type_info() {
    return ATHENA_RTTI_COMPLETE_TYPE_LIST(X) nullptr;
}
#undef X

template<typename T>
ATHENA_API const type_info_t*
type_info(T &item)
{
    (void)item;
    return(type_info<T>());
}

ATHENA_API const attribute_info_list_t*
get_attribute_list(char *name)
{
    const attribute_info_list_t *result = null;

    int name_len = strlen(name);
    for(const attribute_info_list_t &info_list: complete_attribute_array)
    {
        int our_length = strlen(info_list.attribute_name); 
        if(our_length == name_len)
        {
            if(memcmp(info_list.attribute_name, name, our_length) == 0)
            {
                result = &info_list;
                break;
            }
        }
    }

    return(result);
}

}

#endif // ATHENA_IMPLEMENTATION
#endif
