// THIS FILE IS GENERATED BY THE ATHENA REFLECTOR
// DO NOT EDIT!!!!!!

#if !defined(ATHENA_GENERATED_FILE_H)
#define ATHENA_GENERATED_FILE_H

#define ATHENA_RTTI_COMPLETE_TYPE_LIST(X) \
	X(unsigned int, TYPE_unsigned_int, &DEFAULT_type_unsigned_int, "unsigned int") \
	X(unsigned char, TYPE_unsigned_char, &DEFAULT_type_unsigned_char, "unsigned char") \
	X(short, TYPE_short, &DEFAULT_type_short, "short") \
	X(long, TYPE_long, &DEFAULT_type_long, "long") \
	X(int, TYPE_int, &DEFAULT_type_int, "int") \
	X(char, TYPE_char, &DEFAULT_type_char, "char") \
	X(float, TYPE_float, &DEFAULT_type_float, "float") \
	X(double, TYPE_double, &DEFAULT_type_double, "double") \
	X(void, TYPE_void, &DEFAULT_type_void, "void") \
	X(bool, TYPE_bool, &DEFAULT_type_bool, "bool") \
	X(int8_t, TYPE_int8_t, &DEFAULT_type_int8_t, "int8_t") \
	X(int16_t, TYPE_int16_t, &DEFAULT_type_int16_t, "int16_t") \
	X(int32_t, TYPE_int32_t, &DEFAULT_type_int32_t, "int32_t") \
	X(int64_t, TYPE_int64_t, &DEFAULT_type_int64_t, "int64_t") \
	X(uint8_t, TYPE_uint8_t, &DEFAULT_type_uint8_t, "uint8_t") \
	X(uint16_t, TYPE_uint16_t, &DEFAULT_type_uint16_t, "uint16_t") \
	X(uint32_t, TYPE_uint32_t, &DEFAULT_type_uint32_t, "uint32_t") \
	X(uint64_t, TYPE_uint64_t, &DEFAULT_type_uint64_t, "uint64_t") \
	X(size_t, TYPE_size_t, &DEFAULT_type_size_t, "size_t") \
	X(item, TYPE_item, &DEFAULT_type_structure_item, "item") \
	X(other_item_group, TYPE_other_item_group, &DEFAULT_type_structure_other_item_group, "other_item_group") \
	X(get_item, TYPE_get_item, &DEFAULT_type_procedure_get_item, "get_item") \


enum athena_program_types {
    #define X(cpp_type, type_id, structure, string) type_id,
    ATHENA_RTTI_COMPLETE_TYPE_LIST(X)
    #undef X
};


#include <string.h>


struct type_info_t;
struct type_info_member_t;
struct type_info_struct_t;
struct type_info_procedure_t;

enum athena_reflection_type 
{
    ATHENA_METATYPE_INFO_PRIMITIVE,
    ATHENA_METATYPE_INFO_STRUCT,
    ATHENA_METATYPE_INFO_ENUM,
    ATHENA_METATYPE_INFO_PROCEDURE,
};

enum athena_evaluated_type 
{
    ATHENA_TYPE_INT32,
    ATHENA_TYPE_INT64,
    ATHENA_TYPE_UNSIGNED32,
    ATHENA_TYPE_UNSIGNED64,
    ATHENA_TYPE_FLOAT32,
    ATHENA_TYPE_FLOAT64,
    ATHENA_TYPE_STRING,
};

struct type_default_value_t 
{
    unsigned int type;
    union {
        int                int32;
        long long          int64;
        unsigned int       u32;
        unsigned long long u64;
        float              float32;
        double             float64;
        const char        *string;
    };
};

struct type_info_t
{
    const char  *type_name;
    type_info_t *alias_of;
    type_info_t *next_overload;
    unsigned int metatype;
    unsigned int type_id;
    unsigned int size;
};

struct type_info_member_t
{
    const type_info_t        *type_info;
    const char               *member_name;
    const type_info_struct_t *parent;
    unsigned int              offset;
    //unsigned_int            array_size;
    unsigned int              flags;
    unsigned int              pointer_depth;

    type_default_value_t      value;
};

struct type_info_struct_t
{
    const type_info_t type_info;
    unsigned int      member_count;
};

struct type_info_procedure_t
{
    type_info_t               type_info;
    unsigned int              argument_count;
    const type_info_t        *return_type;
    const type_info_member_t *arguments;
};

struct athena_reflection_bundle_t
{
    const type_info_t *type_info_array;
    unsigned int       type_info_array_size;
};

// function
void athena_handle_type_info(const char *filepath, int directory, int recursive);

#ifdef ATHENA_IMPLEMENTATION
# define ATHENA_API 
#else
#define ATHENA_API extern
#endif

#if !defined(ATHENA_RTTI_COMPLETE_TYPE_LIST)
#define ATHENA_RTTI_COMPLETE_TYPE_LIST(X)
#endif

#if !defined(OffsetOf)
#define MemberHelper(type, member) (((type *)0)->member)
#define OffsetOf_(type, member)    (&MemberHelper(type, member))
#define OffsetOf(type, member)     (IntFromPtr(OffsetOf_(type, member)))
#endif

extern const type_info_t *athena_type_information_array[];
struct type_info_struct_item {
	const type_info_t type_info;
	unsigned int member_count;
	union {
		const type_info_member_t member_array[5];
		struct {
			const type_info_member_t item_member;
			const type_info_member_t item_member_one;
			const type_info_member_t other_item_group;
			const type_info_member_t get_item;
			const type_info_member_t item_member_one;
		}members;
	};
};

struct type_info_struct_other_item_group {
	const type_info_t type_info;
	unsigned int member_count;
	union {
		const type_info_member_t member_array[2];
		struct {
			const type_info_member_t subitem;
			const type_info_member_t name;
		}members;
	};
};

struct type_info_procedure_get_item {
	const type_info_t  type_info;
	unsigned int       argument_count;
	const type_info_t *return_type;
	union {
		type_info_member_t argument_array[1];
		struct {
			const type_info_member_t name;
		}arguments;
	};
};

constexpr type_info_t DEFAULT_typedata_unsigned_int = {
	.type_name = "unsigned int",
	.type_id = TYPE_unsigned_int,
	.size = sizeof(unsigned int),
};
constexpr type_info_t DEFAULT_typedata_unsigned_char = {
	.type_name = "unsigned char",
	.type_id = TYPE_unsigned_char,
	.size = sizeof(unsigned char),
};
constexpr type_info_t DEFAULT_typedata_short = {
	.type_name = "short",
	.type_id = TYPE_short,
	.size = sizeof(short),
};
constexpr type_info_t DEFAULT_typedata_long = {
	.type_name = "long",
	.type_id = TYPE_long,
	.size = sizeof(long),
};
constexpr type_info_t DEFAULT_typedata_int = {
	.type_name = "int",
	.type_id = TYPE_int,
	.size = sizeof(int),
};
constexpr type_info_t DEFAULT_typedata_char = {
	.type_name = "char",
	.type_id = TYPE_char,
	.size = sizeof(char),
};
constexpr type_info_t DEFAULT_typedata_float = {
	.type_name = "float",
	.type_id = TYPE_float,
	.size = sizeof(float),
};
constexpr type_info_t DEFAULT_typedata_double = {
	.type_name = "double",
	.type_id = TYPE_double,
	.size = sizeof(double),
};
constexpr type_info_t DEFAULT_typedata_void = {
	.type_name = "void",
	.type_id = TYPE_void,
};
constexpr type_info_t DEFAULT_typedata_bool = {
	.type_name = "bool",
	.type_id = TYPE_bool,
	.size = sizeof(bool),
};
constexpr type_info_t DEFAULT_typedata_int8_t = {
	.type_name = "int8_t",
	.type_id = TYPE_int8_t,
	.size = sizeof(int8_t),
};
constexpr type_info_t DEFAULT_typedata_int16_t = {
	.type_name = "int16_t",
	.type_id = TYPE_int16_t,
	.size = sizeof(int16_t),
};
constexpr type_info_t DEFAULT_typedata_int32_t = {
	.type_name = "int32_t",
	.type_id = TYPE_int32_t,
	.size = sizeof(int32_t),
};
constexpr type_info_t DEFAULT_typedata_int64_t = {
	.type_name = "int64_t",
	.type_id = TYPE_int64_t,
	.size = sizeof(int64_t),
};
constexpr type_info_t DEFAULT_typedata_uint8_t = {
	.type_name = "uint8_t",
	.type_id = TYPE_uint8_t,
	.size = sizeof(uint8_t),
};
constexpr type_info_t DEFAULT_typedata_uint16_t = {
	.type_name = "uint16_t",
	.type_id = TYPE_uint16_t,
	.size = sizeof(uint16_t),
};
constexpr type_info_t DEFAULT_typedata_uint32_t = {
	.type_name = "uint32_t",
	.type_id = TYPE_uint32_t,
	.size = sizeof(uint32_t),
};
constexpr type_info_t DEFAULT_typedata_uint64_t = {
	.type_name = "uint64_t",
	.type_id = TYPE_uint64_t,
	.size = sizeof(uint64_t),
};
constexpr type_info_t DEFAULT_typedata_size_t = {
	.type_name = "size_t",
	.type_id = TYPE_size_t,
	.size = sizeof(size_t),
};
constexpr type_info_struct_item DEFAULT_typedata_structure_item = {
	.type_info = {
		.type_name = "item",
		.type_id = TYPE_item,
		.size = sizeof(item),
	},
	.member_count = 5,
	.members = {
		.item_member = {
			.type_info     = athena_type_information_array[TYPE_int],
			.member_name   = "item_member",
			.parent        = static_cast<type_info_struct_t*>(&DEFAULT_type_structure_item),
			.offset        = OffsetOf(item, item_member),
			.flags         = 0,
			.pointer_depth = 0,
		},
		.item_member_one = {
			.type_info     = athena_type_information_array[TYPE_int],
			.member_name   = "item_member_one",
			.parent        = static_cast<type_info_struct_t*>(&DEFAULT_type_structure_item),
			.offset        = OffsetOf(item, item_member_one),
			.flags         = 0,
			.pointer_depth = 0,
		},
		.other_item_group = {
			.type_info     = athena_type_information_array[TYPE_other_item_group],
			.member_name   = "other_item_group",
			.parent        = static_cast<type_info_struct_t*>(&DEFAULT_type_structure_item),
			.flags         = 0,
			.pointer_depth = 0,
		},
		.get_item = {
			.type_info     = athena_type_information_array[TYPE_get_item],
			.member_name   = "get_item",
			.parent        = static_cast<type_info_struct_t*>(&DEFAULT_type_structure_item),
			.flags         = 1024,
			.pointer_depth = 0,
		},
		.item_member_one = {
			.type_info     = athena_type_information_array[TYPE_int],
			.member_name   = "item_member_one",
			.parent        = static_cast<type_info_struct_t*>(&DEFAULT_type_structure_item),
			.offset        = OffsetOf(item, item_member_one),
			.flags         = 0,
			.pointer_depth = 0,
		},
	},
};

constexpr type_info_struct_other_item_group DEFAULT_typedata_structure_other_item_group = {
	.type_info = {
		.type_name = "other_item_group",
		.type_id = TYPE_other_item_group,
		.size = sizeof(other_item_group),
	},
	.member_count = 2,
	.members = {
		.subitem = {
			.type_info     = athena_type_information_array[TYPE_item],
			.member_name   = "subitem",
			.parent        = static_cast<type_info_struct_t*>(&DEFAULT_type_structure_other_item_group),
			.offset        = OffsetOf(other_item_group, subitem),
			.flags         = 2,
			.pointer_depth = 1,
		},
		.name = {
			.type_info     = athena_type_information_array[TYPE_char],
			.member_name   = "name",
			.parent        = static_cast<type_info_struct_t*>(&DEFAULT_type_structure_other_item_group),
			.offset        = OffsetOf(other_item_group, name),
			.flags         = 2,
			.pointer_depth = 1,
		},
	},
};

constexpr type_info_procedure_get_item DEFAULT_typedata_procedure_get_item = {
	.type_info = {
		.type_name = "get_item",
		.type_id = TYPE_get_item,
	},
	.return_type    = athena_type_information_array[TYPE_item],
	.argument_count = 1,
	.arguments = {
		.name = {
			.type_info     = athena_type_information_array[TYPE_char],
			.member_name   = "name",
			.parent        = static_cast<type_info_struct_t*>(&DEFAULT_type_structure_get_item),
			.flags         = 2,
			.pointer_depth = 1,
		},
	},
};
constexpr type_info_t *athena_type_information_array[] = {
	&DEFAULT_typedata_unsigned_int
	&DEFAULT_typedata_unsigned_char
	&DEFAULT_typedata_short
	&DEFAULT_typedata_long
	&DEFAULT_typedata_int
	&DEFAULT_typedata_char
	&DEFAULT_typedata_float
	&DEFAULT_typedata_double
	&DEFAULT_typedata_void
	&DEFAULT_typedata_bool
	&DEFAULT_typedata_int8_t
	&DEFAULT_typedata_int16_t
	&DEFAULT_typedata_int32_t
	&DEFAULT_typedata_int64_t
	&DEFAULT_typedata_uint8_t
	&DEFAULT_typedata_uint16_t
	&DEFAULT_typedata_uint32_t
	&DEFAULT_typedata_uint64_t
	&DEFAULT_typedata_size_t
	&DEFAULT_typedata_structure_item
	&DEFAULT_typedata_structure_other_item_group
	&DEFAULT_typedata_procedure_get_item
};


ATHENA_API inline const type_info_t *type_info(unsigned long long type_id);
ATHENA_API inline const type_info_t *type_info(const char *string);

#ifdef C_STRING_H
ATHENA_API inline const type_info_t *type_info(string_t string);
#endif

// NOTE(Sleepster): STB style lib
#ifdef ATHENA_IMPLMENETATION 

ATHENA_API inline const type_info_t*
type_info(unsigned long long type_id)
{
    const type_info_t *result = static_cast<const type_info_t*>(athena_type_information_array[type_id]);
    return(result);
};

#ifdef C_STRING_H
ATHENA_API inline const type_info_t*
type_info(string_t string)
{
    const type_info_t *result = null;
    if(string.count > 0)
    {
        for(auto &element: athena_type_information_array)
        {
            if(c_string_compare(STR(element.type_name), string))
            {
                result = &element;
                break;
            }
        }
    }

    return(result);
}

ATHENA_API inline const type_info_member_t*
athena_get_member_info(const type_info_t *type_info, string_t member_name) 
{
    const type_info_member_t *result = null;

    if(member_name.count > 0)
    {
        const type_info_struct_t *structure_info = static_cast<const type_info_struct_t*>(type_info);
        for(u32 member_index = 0;
            member_index < structure_info->member_count;
            ++member_index)
        {
            const type_info_member_t *member = structure_info->member_array[member_index];
            if(c_string_compare(STR(member->member_name), member_name))
            {
                result = static_cast<const type_info_t*>(member);
                break;
            }
        }
    }

    return(result);
}
#endif

#ifndef ArrayCount
#define ArrayCount(x) (sizeof(x) / sizeof((x[0])))
#endif

ATHENA_API inline const type_info_t*
type_info(const char *string)
{
    const type_info_t *result = nullptr;

    int string_length = strlen(string);
    if(string_length > 0)
    {
        for(unsigned int index = 0;
            index < ArrayCount(athena_type_information_array);
            ++index)
        {
            const type_info_t *element = athena_type_information_array[index];

            int element_length = strlen(element->type_name);
            if(string_length != element_length) continue;
            if(memcmp(element->type_name, string, element_length) == 0)
            {
                result = element;
                break;
            }
        }
    }

    return(result);
}

ATHENA_API inline const type_info_member_t*
athena_get_member_info(const type_info_t *type_info, const char *member_name) 
{
    const type_info_member_t *result = nullptr;

    int name_length = strlen(member_name);
    if(name_length > 0)
    {
        const type_info_struct_t *structure_info = static_cast<const type_info_struct_t*>(type_info);
        for(unsigned int member_index = 0;
            member_index < structure_info->member_count;
            ++member_index)
        {
            const type_info_member_t *member = structure_info->members + member_index;

            int member_length = strlen(member->member_name);
            if(member_length != name_length) continue;

            if(memcmp(member_name, member->member_name, member_length) == 0)
            {
                result = member;
                break;
            }
        }
    }

    return(result);
}

ATHENA_API inline const type_info_struct_t*
athena_get_struct_info_from_member(const type_info_t *info)
{
    const type_info_struct_t *result = nullptr;
    const type_info_member_t *member = static_cast<const type_info_member_t*>(info);
    if(member->parent)
    {
        result = member->parent;
    }

    return(result);
}

ATHENA_API inline const type_info_struct_t*
athena_get_struct_info_from_member(const type_info_member_t *member)
{
    const type_info_struct_t *result = nullptr;
    if(member->parent)
    {
        result = member->parent;
    }

    return(result);
}

#endif // ATHENA_IMPLEMENTATION
#endif
