// THIS FILE IS AUTOGENERATED FROM FILE: 'immediate_vertex.slh'...
// DO NOT EDIT!!!!!
#ifndef IMMEDIATE_VERTEX_SLH
#define IMMEDIATE_VERTEX_SLH

#include <c_math.h>
#include <c_types.h>

typedef vec2_t float2;
typedef vec3_t float3;
typedef vec4_t float4;

typedef mat2_t float2x2;
typedef mat3_t float3x3;
typedef mat4_t float4x4;

typedef u32    uint;

struct alignas(16) vImmediateVertex_t {
	float4 vPosition;
	float4 vColor;
	float2 vTexCoord;
	float2 vPadding;
	float2 vSDFInfo;
	float2 vPadding0;
};
#endif // IMMEDIATE_VERTEX_SLH
