// THIS IS GENERATED BY THE PREPROCESSOR
// THIS IS THE RTTI FOR THE ENTIRE PROGRAM

#ifndef GENERATED_PROGRAM_TYPES_H
#define GENERATED_PROGRAM_TYPES_H

#include <preprocessor_type_data.h>

enum GENERATED_program_types_t {
	TYPE_render_pipeline_state_t,
	TYPE_bool32,
	TYPE_u32,
};

struct type_info_render_pipeline_state_t {
	const char *name;
	u32 type;
	u32 member_count;
	struct {
		type_info_member_t blend_enabled;
		type_info_member_t src_color_blend_mode;
		type_info_member_t dst_color_blend_mode;
		type_info_member_t src_alpha_blend_mode;
		type_info_member_t dst_alpha_blend_mode;
		type_info_member_t color_blend_op;
		type_info_member_t alpha_blend_op;
		type_info_member_t depth_testing_enabled;
		type_info_member_t depth_writing_enabled;
		type_info_member_t depth_func;
		type_info_member_t stencil_enabled;
		type_info_member_t stencil_state;
		type_info_member_t stencil_keep;
	}members;
};


const static type_info_render_pipeline_state_t type_info_render_pipeline_state_t = {
	.name = "render_pipeline_state_t",
	.type = TYPE_render_pipeline_state_t,
	.member_count = 13,
	.members = {
		.blend_enabled = {.name = "blend_enabled", .type = TYPE_bool32, .offset = offsetof(render_pipeline_state_t, blend_enabled), .size = sizeof(bool32)},
		.src_color_blend_mode = {.name = "src_color_blend_mode", .type = TYPE_u32, .offset = offsetof(render_pipeline_state_t, src_color_blend_mode), .size = sizeof(u32)},
		.dst_color_blend_mode = {.name = "dst_color_blend_mode", .type = TYPE_u32, .offset = offsetof(render_pipeline_state_t, dst_color_blend_mode), .size = sizeof(u32)},
		.src_alpha_blend_mode = {.name = "src_alpha_blend_mode", .type = TYPE_u32, .offset = offsetof(render_pipeline_state_t, src_alpha_blend_mode), .size = sizeof(u32)},
		.dst_alpha_blend_mode = {.name = "dst_alpha_blend_mode", .type = TYPE_u32, .offset = offsetof(render_pipeline_state_t, dst_alpha_blend_mode), .size = sizeof(u32)},
		.color_blend_op = {.name = "color_blend_op", .type = TYPE_u32, .offset = offsetof(render_pipeline_state_t, color_blend_op), .size = sizeof(u32)},
		.alpha_blend_op = {.name = "alpha_blend_op", .type = TYPE_u32, .offset = offsetof(render_pipeline_state_t, alpha_blend_op), .size = sizeof(u32)},
		.depth_testing_enabled = {.name = "depth_testing_enabled", .type = TYPE_bool32, .offset = offsetof(render_pipeline_state_t, depth_testing_enabled), .size = sizeof(bool32)},
		.depth_writing_enabled = {.name = "depth_writing_enabled", .type = TYPE_u32, .offset = offsetof(render_pipeline_state_t, depth_writing_enabled), .size = sizeof(u32)},
		.depth_func = {.name = "depth_func", .type = TYPE_u32, .offset = offsetof(render_pipeline_state_t, depth_func), .size = sizeof(u32)},
		.stencil_enabled = {.name = "stencil_enabled", .type = TYPE_bool32, .offset = offsetof(render_pipeline_state_t, stencil_enabled), .size = sizeof(bool32)},
		.stencil_state = {.name = "stencil_state", .type = TYPE_u32, .offset = offsetof(render_pipeline_state_t, stencil_state), .size = sizeof(u32)},
		.stencil_keep = {.name = "stencil_keep", .type = TYPE_u32, .offset = offsetof(render_pipeline_state_t, stencil_keep), .size = sizeof(u32)},
	}
};

#endif // GENERATED_PROGRAM_TYPES_H

