// THIS IS GENERATED BY THE PREPROCESSOR
// THIS IS THE RTTI FOR THE ENTIRE PROGRAM

#ifndef GENERATED_PROGRAM_TYPES_H
#define GENERATED_PROGRAM_TYPES_H

#include <preprocessor_type_data.h>

#pragma pack(push, 1)

enum GENERATED_program_types_t {
	TYPE_MAX_RENDER_GROUPS_t,
	TYPE_renderer_effect_application_flags_t,
	TYPE_render_pipeline_blending_mode_t,
	TYPE_render_pipeline_blending_equation_t,
	TYPE_render_pipeline_depth_function_t,
	TYPE_render_pipeline_state_t,
	TYPE_bool32,
	TYPE_u32,
	TYPE_material_instance_t,
	TYPE_u64,
	TYPE_string_t,
	TYPE_asset_handle_t,
	TYPE_vulkan_shader_uniform_data_t,
	TYPE_material_archetype_t,
};

struct type_info_render_pipeline_state_t {
	const char *name;
	u32 type;
	u32 member_count;
	struct {
		type_info_member_t blend_enabled;
		type_info_member_t src_color_blend_mode;
		type_info_member_t dst_color_blend_mode;
		type_info_member_t src_alpha_blend_mode;
		type_info_member_t dst_alpha_blend_mode;
		type_info_member_t color_blend_op;
		type_info_member_t alpha_blend_op;
		type_info_member_t depth_testing_enabled;
		type_info_member_t depth_writing_enabled;
		type_info_member_t depth_func;
		type_info_member_t stencil_enabled;
		type_info_member_t stencil_state;
		type_info_member_t stencil_keep;
	}members;
};

struct type_info_material_instance_t {
	const char *name;
	u32 type;
	u32 member_count;
	struct {
		type_info_member_t ID;
		type_info_member_t version;
		type_info_member_t name;
		type_info_member_t textures;
		type_info_member_t pipeline_state;
		type_info_member_t renderer_effect_flags;
		type_info_member_t shader_uniform_count;
		type_info_member_t uniform_data;
		type_info_member_t archetype;
	}members;
};

struct type_info_material_archetype_t {
	const char *name;
	u32 type;
	u32 member_count;
	struct {
		type_info_member_t ID;
		type_info_member_t version;
		type_info_member_t name;
		type_info_member_t shader_binary_name;
		type_info_member_t shader_handle;
		type_info_member_t base_instance;
	}members;
};


struct type_info_enum_renderer_effect_application_flags_t {
	const char *name;
	u32 type;
	u32 member_count;
	struct {
		type_info_member_t REAF_None;
		type_info_member_t REAF_Bloom;
		type_info_member_t REAF_Emmision;
		type_info_member_t REAF_Vignette;
		type_info_member_t REAF_FilmGrain;
		type_info_member_t REAF_Count;
	}members;
};

struct type_info_enum_render_pipeline_blending_mode_t {
	const char *name;
	u32 type;
	u32 member_count;
	struct {
		type_info_member_t RBM_Invalid;
		type_info_member_t RBM_Zero;
		type_info_member_t RBM_One;
		type_info_member_t RBM_Constant;
		type_info_member_t RBM_SrcColor;
		type_info_member_t RBM_OneMinusSrcColor;
		type_info_member_t RBM_DstColor;
		type_info_member_t RBM_OneMinusDstColor;
		type_info_member_t RBM_SrcAlpha;
		type_info_member_t RBM_OneMinusSrcAlpha;
		type_info_member_t RBM_DstAlpha;
		type_info_member_t RBM_OneMinusDstAlpha;
		type_info_member_t RBM_Count;
	}members;
};

struct type_info_enum_render_pipeline_blending_equation_t {
	const char *name;
	u32 type;
	u32 member_count;
	struct {
		type_info_member_t RBE_Invalid;
		type_info_member_t RBE_Add;
		type_info_member_t RBE_Subtract;
		type_info_member_t RBE_ReverseSubtract;
		type_info_member_t RBE_Min;
		type_info_member_t RBE_Max;
	}members;
};

struct type_info_enum_render_pipeline_depth_function_t {
	const char *name;
	u32 type;
	u32 member_count;
	struct {
		type_info_member_t RDF_Invalid;
		type_info_member_t RDF_Never;
		type_info_member_t RDF_Always;
		type_info_member_t RDF_Greater;
		type_info_member_t RDF_Less;
		type_info_member_t RDF_Equal;
		type_info_member_t RDF_NotEqual;
		type_info_member_t RDF_LessOrEqual;
		type_info_member_t RDF_GreaterOrEqual;
		type_info_member_t RDF_Count;
	}members;
};


const static type_info_enum_renderer_effect_application_flags_t type_info_enum_renderer_effect_application_flags_t = {
	.name = "renderer_effect_application_flags_t",
	.type = TYPE_renderer_effect_application_flags_t,
	.member_count = 6,
	.members = {
		.REAF_None = {.name = "REAF_None", .type = TYPE_renderer_effect_application_flags_t, .offset = REAF_None, .size = 0},
		.REAF_Bloom = {.name = "REAF_Bloom", .type = TYPE_renderer_effect_application_flags_t, .offset = REAF_Bloom, .size = 0},
		.REAF_Emmision = {.name = "REAF_Emmision", .type = TYPE_renderer_effect_application_flags_t, .offset = REAF_Emmision, .size = 0},
		.REAF_Vignette = {.name = "REAF_Vignette", .type = TYPE_renderer_effect_application_flags_t, .offset = REAF_Vignette, .size = 0},
		.REAF_FilmGrain = {.name = "REAF_FilmGrain", .type = TYPE_renderer_effect_application_flags_t, .offset = REAF_FilmGrain, .size = 0},
		.REAF_Count = {.name = "REAF_Count", .type = TYPE_renderer_effect_application_flags_t, .offset = REAF_Count, .size = 0},
	}
};

const static type_info_enum_render_pipeline_blending_mode_t type_info_enum_render_pipeline_blending_mode_t = {
	.name = "render_pipeline_blending_mode_t",
	.type = TYPE_render_pipeline_blending_mode_t,
	.member_count = 13,
	.members = {
		.RBM_Invalid = {.name = "RBM_Invalid", .type = TYPE_render_pipeline_blending_mode_t, .offset = RBM_Invalid, .size = 0},
		.RBM_Zero = {.name = "RBM_Zero", .type = TYPE_render_pipeline_blending_mode_t, .offset = RBM_Zero, .size = 0},
		.RBM_One = {.name = "RBM_One", .type = TYPE_render_pipeline_blending_mode_t, .offset = RBM_One, .size = 0},
		.RBM_Constant = {.name = "RBM_Constant", .type = TYPE_render_pipeline_blending_mode_t, .offset = RBM_Constant, .size = 0},
		.RBM_SrcColor = {.name = "RBM_SrcColor", .type = TYPE_render_pipeline_blending_mode_t, .offset = RBM_SrcColor, .size = 0},
		.RBM_OneMinusSrcColor = {.name = "RBM_OneMinusSrcColor", .type = TYPE_render_pipeline_blending_mode_t, .offset = RBM_OneMinusSrcColor, .size = 0},
		.RBM_DstColor = {.name = "RBM_DstColor", .type = TYPE_render_pipeline_blending_mode_t, .offset = RBM_DstColor, .size = 0},
		.RBM_OneMinusDstColor = {.name = "RBM_OneMinusDstColor", .type = TYPE_render_pipeline_blending_mode_t, .offset = RBM_OneMinusDstColor, .size = 0},
		.RBM_SrcAlpha = {.name = "RBM_SrcAlpha", .type = TYPE_render_pipeline_blending_mode_t, .offset = RBM_SrcAlpha, .size = 0},
		.RBM_OneMinusSrcAlpha = {.name = "RBM_OneMinusSrcAlpha", .type = TYPE_render_pipeline_blending_mode_t, .offset = RBM_OneMinusSrcAlpha, .size = 0},
		.RBM_DstAlpha = {.name = "RBM_DstAlpha", .type = TYPE_render_pipeline_blending_mode_t, .offset = RBM_DstAlpha, .size = 0},
		.RBM_OneMinusDstAlpha = {.name = "RBM_OneMinusDstAlpha", .type = TYPE_render_pipeline_blending_mode_t, .offset = RBM_OneMinusDstAlpha, .size = 0},
		.RBM_Count = {.name = "RBM_Count", .type = TYPE_render_pipeline_blending_mode_t, .offset = RBM_Count, .size = 0},
	}
};

const static type_info_enum_render_pipeline_blending_equation_t type_info_enum_render_pipeline_blending_equation_t = {
	.name = "render_pipeline_blending_equation_t",
	.type = TYPE_render_pipeline_blending_equation_t,
	.member_count = 6,
	.members = {
		.RBE_Invalid = {.name = "RBE_Invalid", .type = TYPE_render_pipeline_blending_equation_t, .offset = RBE_Invalid, .size = 0},
		.RBE_Add = {.name = "RBE_Add", .type = TYPE_render_pipeline_blending_equation_t, .offset = RBE_Add, .size = 0},
		.RBE_Subtract = {.name = "RBE_Subtract", .type = TYPE_render_pipeline_blending_equation_t, .offset = RBE_Subtract, .size = 0},
		.RBE_ReverseSubtract = {.name = "RBE_ReverseSubtract", .type = TYPE_render_pipeline_blending_equation_t, .offset = RBE_ReverseSubtract, .size = 0},
		.RBE_Min = {.name = "RBE_Min", .type = TYPE_render_pipeline_blending_equation_t, .offset = RBE_Min, .size = 0},
		.RBE_Max = {.name = "RBE_Max", .type = TYPE_render_pipeline_blending_equation_t, .offset = RBE_Max, .size = 0},
	}
};

const static type_info_enum_render_pipeline_depth_function_t type_info_enum_render_pipeline_depth_function_t = {
	.name = "render_pipeline_depth_function_t",
	.type = TYPE_render_pipeline_depth_function_t,
	.member_count = 10,
	.members = {
		.RDF_Invalid = {.name = "RDF_Invalid", .type = TYPE_render_pipeline_depth_function_t, .offset = RDF_Invalid, .size = 0},
		.RDF_Never = {.name = "RDF_Never", .type = TYPE_render_pipeline_depth_function_t, .offset = RDF_Never, .size = 0},
		.RDF_Always = {.name = "RDF_Always", .type = TYPE_render_pipeline_depth_function_t, .offset = RDF_Always, .size = 0},
		.RDF_Greater = {.name = "RDF_Greater", .type = TYPE_render_pipeline_depth_function_t, .offset = RDF_Greater, .size = 0},
		.RDF_Less = {.name = "RDF_Less", .type = TYPE_render_pipeline_depth_function_t, .offset = RDF_Less, .size = 0},
		.RDF_Equal = {.name = "RDF_Equal", .type = TYPE_render_pipeline_depth_function_t, .offset = RDF_Equal, .size = 0},
		.RDF_NotEqual = {.name = "RDF_NotEqual", .type = TYPE_render_pipeline_depth_function_t, .offset = RDF_NotEqual, .size = 0},
		.RDF_LessOrEqual = {.name = "RDF_LessOrEqual", .type = TYPE_render_pipeline_depth_function_t, .offset = RDF_LessOrEqual, .size = 0},
		.RDF_GreaterOrEqual = {.name = "RDF_GreaterOrEqual", .type = TYPE_render_pipeline_depth_function_t, .offset = RDF_GreaterOrEqual, .size = 0},
		.RDF_Count = {.name = "RDF_Count", .type = TYPE_render_pipeline_depth_function_t, .offset = RDF_Count, .size = 0},
	}
};


const static type_info_render_pipeline_state_t type_info_render_pipeline_state_t = {
	.name = "render_pipeline_state_t",
	.type = TYPE_render_pipeline_state_t,
	.member_count = 13,
	.members = {
		.blend_enabled = {.name = "blend_enabled", .type = TYPE_bool32, .offset = offsetof(render_pipeline_state_t, blend_enabled), .size = sizeof(bool32)},
		.src_color_blend_mode = {.name = "src_color_blend_mode", .type = TYPE_u32, .offset = offsetof(render_pipeline_state_t, src_color_blend_mode), .size = sizeof(u32)},
		.dst_color_blend_mode = {.name = "dst_color_blend_mode", .type = TYPE_u32, .offset = offsetof(render_pipeline_state_t, dst_color_blend_mode), .size = sizeof(u32)},
		.src_alpha_blend_mode = {.name = "src_alpha_blend_mode", .type = TYPE_u32, .offset = offsetof(render_pipeline_state_t, src_alpha_blend_mode), .size = sizeof(u32)},
		.dst_alpha_blend_mode = {.name = "dst_alpha_blend_mode", .type = TYPE_u32, .offset = offsetof(render_pipeline_state_t, dst_alpha_blend_mode), .size = sizeof(u32)},
		.color_blend_op = {.name = "color_blend_op", .type = TYPE_u32, .offset = offsetof(render_pipeline_state_t, color_blend_op), .size = sizeof(u32)},
		.alpha_blend_op = {.name = "alpha_blend_op", .type = TYPE_u32, .offset = offsetof(render_pipeline_state_t, alpha_blend_op), .size = sizeof(u32)},
		.depth_testing_enabled = {.name = "depth_testing_enabled", .type = TYPE_bool32, .offset = offsetof(render_pipeline_state_t, depth_testing_enabled), .size = sizeof(bool32)},
		.depth_writing_enabled = {.name = "depth_writing_enabled", .type = TYPE_bool32, .offset = offsetof(render_pipeline_state_t, depth_writing_enabled), .size = sizeof(bool32)},
		.depth_func = {.name = "depth_func", .type = TYPE_u32, .offset = offsetof(render_pipeline_state_t, depth_func), .size = sizeof(u32)},
		.stencil_enabled = {.name = "stencil_enabled", .type = TYPE_bool32, .offset = offsetof(render_pipeline_state_t, stencil_enabled), .size = sizeof(bool32)},
		.stencil_state = {.name = "stencil_state", .type = TYPE_u32, .offset = offsetof(render_pipeline_state_t, stencil_state), .size = sizeof(u32)},
		.stencil_keep = {.name = "stencil_keep", .type = TYPE_u32, .offset = offsetof(render_pipeline_state_t, stencil_keep), .size = sizeof(u32)},
	}
};

const static type_info_material_instance_t type_info_material_instance_t = {
	.name = "material_instance_t",
	.type = TYPE_material_instance_t,
	.member_count = 9,
	.members = {
		.ID = {.name = "ID", .type = TYPE_u64, .offset = offsetof(material_instance_t, ID), .size = sizeof(u64)},
		.version = {.name = "version", .type = TYPE_u32, .offset = offsetof(material_instance_t, version), .size = sizeof(u32)},
		.name = {.name = "name", .type = TYPE_string_t, .offset = offsetof(material_instance_t, name), .size = sizeof(string_t)},
		.textures = {.name = "textures", .type = TYPE_asset_handle_t, .offset = offsetof(material_instance_t, textures), .size = sizeof(asset_handle_t)},
		.pipeline_state = {.name = "pipeline_state", .type = TYPE_render_pipeline_state_t, .offset = offsetof(material_instance_t, pipeline_state), .size = sizeof(render_pipeline_state_t)},
		.renderer_effect_flags = {.name = "renderer_effect_flags", .type = TYPE_u32, .offset = offsetof(material_instance_t, renderer_effect_flags), .size = sizeof(u32)},
		.shader_uniform_count = {.name = "shader_uniform_count", .type = TYPE_u32, .offset = offsetof(material_instance_t, shader_uniform_count), .size = sizeof(u32)},
		.uniform_data = {.name = "uniform_data", .type = TYPE_vulkan_shader_uniform_data_t, .offset = offsetof(material_instance_t, uniform_data), .size = sizeof(vulkan_shader_uniform_data_t*)},
		.archetype = {.name = "archetype", .type = TYPE_material_archetype_t, .offset = offsetof(material_instance_t, archetype), .size = sizeof(material_archetype_t*)},
	}
};

const static type_info_material_archetype_t type_info_material_archetype_t = {
	.name = "material_archetype_t",
	.type = TYPE_material_archetype_t,
	.member_count = 6,
	.members = {
		.ID = {.name = "ID", .type = TYPE_u64, .offset = offsetof(material_archetype_t, ID), .size = sizeof(u64)},
		.version = {.name = "version", .type = TYPE_u32, .offset = offsetof(material_archetype_t, version), .size = sizeof(u32)},
		.name = {.name = "name", .type = TYPE_string_t, .offset = offsetof(material_archetype_t, name), .size = sizeof(string_t)},
		.shader_binary_name = {.name = "shader_binary_name", .type = TYPE_string_t, .offset = offsetof(material_archetype_t, shader_binary_name), .size = sizeof(string_t)},
		.shader_handle = {.name = "shader_handle", .type = TYPE_asset_handle_t, .offset = offsetof(material_archetype_t, shader_handle), .size = sizeof(asset_handle_t)},
		.base_instance = {.name = "base_instance", .type = TYPE_material_instance_t, .offset = offsetof(material_archetype_t, base_instance), .size = sizeof(material_instance_t)},
	}
};

#pragma pack(pop)

#endif // GENERATED_PROGRAM_TYPES_H

