// THIS FILE IS AUTOGENERATED FROM FILE: 'widget_instance_data.slh'...
// DO NOT EDIT!!!!!
#ifndef WIDGET_INSTANCE_DATA_SLH
#define WIDGET_INSTANCE_DATA_SLH

#include <c_math.h>
#include <c_types.h>

typedef vec2_t float2;
typedef vec3_t float3;
typedef vec4_t float4;

typedef mat2_t float2x2;
typedef mat3_t float3x3;
typedef mat4_t float4x4;

typedef uint   u32;
typedef int    s32;
typedef float  float32;

struct alignas(16) ImmediateWidgetData_t {
	float2 iHalfSize;
	float iRadius;
	uint iFlags;
	float4 iBorderColor;
	float iBorderThickness;
	float iSDFSmoothness;
	float2 iPadding__;
};
#endif // WIDGET_INSTANCE_DATA_SLH
