// THIS FILE IS GENERATED BY METAPROGRAM.EXE...
// IT CONTAINS ALL THE RTTI NEEDED FOR THE PROGRAM...

#if !defined(GENERATED_PROGRAM_RTTI_H)
#define GENERATED_PROGRAM_RTTI_H

#define GENERATED_PROGRAM_TYPE_LIST(X) \
	X(TYPE_za_allocation_tag_t, "za_allocation_tag_t") \
	X(TYPE_u32, "u32") \
	X(TYPE_bool8, "bool8") \
	X(TYPE_u64, "u64") \
	X(TYPE_zone_allocator_block_t, "zone_allocator_block_t") \
	X(TYPE_sys_mutex_t, "sys_mutex_t") \
	X(TYPE_u8, "u8") \
	X(TYPE_zone_allocator_block_t, "zone_allocator_block_t") \
	X(TYPE_zone_allocator_t, "zone_allocator_t") \


enum GENERATED_program_type_t { 
#define X(enum, string) enum,  
GENERATED_PROGRAM_TYPE_LIST(X)
#undef X
};


#define META_STRUCT_TYPE_LIST(X) \
    X(META_STRUCT_TYPE_Struct, "struct") \
    X(META_STRUCT_TYPE_Union,  "union") \
    X(META_STRUCT_TYPE_Enum,   "enum")

typedef enum meta_struct_type 
{
    META_STRUCT_TYPE_Invalid,

#define X(enum, string) enum, 
    META_STRUCT_TYPE_LIST(X)
#undef X

    META_STRUCT_TYPE_Count
}meta_struct_type_t;

#define METATYPE_KIND_LIST(X) \
    X(META_TYPE_KIND_Primitive,    "META_TYPE_KIND_Primitive") \
    X(META_TYPE_KIND_Struct,       "META_TYPE_KIND_Struct") \
    X(META_TYPE_KIND_Enum,         "META_TYPE_KIND_Enum") \
    X(META_TYPE_KIND_Array,        "META_TYPE_KIND_Array") \
    X(META_TYPE_KIND_DynamicArray, "META_TYPE_KIND_DynamicArray") \
    X(META_TYPE_KIND_HashTable,    "META_TYPE_KIND_HashTable") \
    X(META_TYPE_KIND_Invalid,      "META_TYPE_KIND_Invalid") 

typedef enum metatype_kind
{
    // NOTE(Sleepster): Default to primitive 
#define X(enum, string) enum,
    METATYPE_KIND_LIST(X)
#undef X

    META_TYPE_KIND_Count
}metatype_kind_t;

#define METATYPE_FLAG_LIST(X) \
    X(META_TYPE_FLAGS_None,      1u << 0, "META_TYPE_FLAGS_None") \
    X(META_TYPE_FLAGS_Constant,  1u << 1, "META_TYPE_FLAGS_Constant") \
    X(META_TYPE_FLAGS_Volatile,  1u << 2, "META_TYPE_FLAGS_Volatile") \
    X(META_TYPE_FLAGS_Static,    1u << 3, "META_TYPE_FLAGS_Static") \
    X(META_TYPE_FLAGS_Pointer,   1u << 4, "META_TYPE_FLAGS_Pointer") \
    X(META_TYPE_FLAGS_Anonymous, 1u << 5, "META_TYPE_FLAGS_Anonymous")

typedef enum metatype_flags
{
#define X(enum, value, string) enum = value,
    METATYPE_FLAG_LIST(X)
#undef X

    META_TYPE_FLAGS_Count
}metatype_flags_t;

typedef struct type_info_member {
    const char     *name; // string
    u32             type; // types enum
                          
    metatype_kind_t kind;
    u32             modifier_flags;
    u32             flag_counter;

    u32             pointer_depth;
    u32             array_size;

    u32             size;
    u32             offset;
}type_info_member_t;

typedef struct type_info_struct {
    const char         *name;           // string
    u32                 type;           // types enum
    metatype_kind_t     kind;           // is it struct? union? enum?
    u32                 modifier_flags; // for anonymous structures

    u32                 size;
    u32                 member_count;
    type_info_member_t *members;
}type_info_struct_t;

typedef struct type_info
{
    const char         *name;
    u32                 type;
    u32                 size;

    type_info_struct_t *struct_info;
}type_info_t;

struct type_info_struct_zone_allocator_block_t {
	const char *name;
	u32 type;
	u32 kind;
	u32 modifier_flags;
	u32 flag_counter;
	u32 element_size;
	u32 member_count;
	union {
		type_info_member_t member_array[6];
		struct {
			type_info_member_t block_id;
			type_info_member_t is_allocated;
			type_info_member_t block_size;
			type_info_member_t allocation_tag;
			type_info_member_t next_block;
			type_info_member_t prev_block;
		}members;
	};
};

struct type_info_struct_zone_allocator_t {
	const char *name;
	u32 type;
	u32 kind;
	u32 modifier_flags;
	u32 flag_counter;
	u32 element_size;
	u32 member_count;
	union {
		type_info_member_t member_array[5];
		struct {
			type_info_member_t mutex;
			type_info_member_t capacity;
			type_info_member_t base;
			type_info_member_t first_block;
			type_info_member_t cursor;
		}members;
	};
};


struct type_info_enum_za_allocation_tag_t {
	const char *name;
	u32 type;
	u32 kind;
	u32 modifier_flags;
	u32 flag_counter;
	u32 element_size;
	u32 member_count;
	union {
		type_info_member_t member_array[7];
		struct {
			type_info_member_t ZA_TAG_NONE;
			type_info_member_t ZA_TAG_STATIC;
			type_info_member_t ZA_TAG_TEXTURE;
			type_info_member_t ZA_TAG_SOUND;
			type_info_member_t ZA_TAG_FONT;
			type_info_member_t ZA_TAG_PURGELEVEL;
			type_info_member_t ZA_TAG_CACHE;
		}members;
	};
};


const static type_info_struct_zone_allocator_block_t type_info_struct_zone_allocator_block_t_const_data = {
	.name = "zone_allocator_block_t,",
	.type = TYPE_zone_allocator_block_t,
	.kind = META_TYPE_KIND_Struct,
	.modifier_flags = META_TYPE_FLAGS_None,
	.flag_counter = 0,
	.element_size = sizeof(zone_allocator_block_t),
	.member_count = 6,
	.members = {
		.block_id = {.name = "u32", .type = TYPE_u32, .kind = META_TYPE_KIND_Primitive, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(zone_allocator_block_t), .offset = offsetof(zone_allocator_block_t, block_id)},
		.is_allocated = {.name = "bool8", .type = TYPE_bool8, .kind = META_TYPE_KIND_Primitive, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(zone_allocator_block_t), .offset = offsetof(zone_allocator_block_t, is_allocated)},
		.block_size = {.name = "u64", .type = TYPE_u64, .kind = META_TYPE_KIND_Primitive, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(zone_allocator_block_t), .offset = offsetof(zone_allocator_block_t, block_size)},
		.allocation_tag = {.name = "u64", .type = TYPE_u64, .kind = META_TYPE_KIND_Primitive, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(zone_allocator_block_t), .offset = offsetof(zone_allocator_block_t, allocation_tag)},
		.next_block = {.name = "zone_allocator_block", .type = TYPE_zone_allocator_block, .kind = META_TYPE_KIND_Struct, .modifier_flags = META_TYPE_FLAGS_Pointer, .flag_counter = 1, .pointer_depth = 1, .array_size = 0, .size = sizeof(zone_allocator_block_t), .offset = offsetof(zone_allocator_block_t, next_block)},
		.prev_block = {.name = "zone_allocator_block", .type = TYPE_zone_allocator_block, .kind = META_TYPE_KIND_Struct, .modifier_flags = META_TYPE_FLAGS_Pointer, .flag_counter = 1, .pointer_depth = 1, .array_size = 0, .size = sizeof(zone_allocator_block_t), .offset = offsetof(zone_allocator_block_t, prev_block)},
	}
};
const static type_info_struct_zone_allocator_t type_info_struct_zone_allocator_t_const_data = {
	.name = "zone_allocator_t,",
	.type = TYPE_zone_allocator_t,
	.kind = META_TYPE_KIND_Struct,
	.modifier_flags = META_TYPE_FLAGS_None,
	.flag_counter = 0,
	.element_size = sizeof(zone_allocator_t),
	.member_count = 5,
	.members = {
		.mutex = {.name = "sys_mutex_t", .type = TYPE_sys_mutex_t, .kind = META_TYPE_KIND_Primitive, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(zone_allocator_t), .offset = offsetof(zone_allocator_t, mutex)},
		.capacity = {.name = "u64", .type = TYPE_u64, .kind = META_TYPE_KIND_Primitive, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(zone_allocator_t), .offset = offsetof(zone_allocator_t, capacity)},
		.base = {.name = "u8", .type = TYPE_u8, .kind = META_TYPE_KIND_Primitive, .modifier_flags = META_TYPE_FLAGS_Pointer, .flag_counter = 1, .pointer_depth = 1, .array_size = 0, .size = sizeof(zone_allocator_t), .offset = offsetof(zone_allocator_t, base)},
		.first_block = {.name = "zone_allocator_block_t", .type = TYPE_zone_allocator_block_t, .kind = META_TYPE_KIND_Primitive, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(zone_allocator_t), .offset = offsetof(zone_allocator_t, first_block)},
		.cursor = {.name = "zone_allocator_block_t", .type = TYPE_zone_allocator_block_t, .kind = META_TYPE_KIND_Primitive, .modifier_flags = META_TYPE_FLAGS_Pointer, .flag_counter = 1, .pointer_depth = 1, .array_size = 0, .size = sizeof(zone_allocator_t), .offset = offsetof(zone_allocator_t, cursor)},
	}
};

const static type_info_enum_za_allocation_tag_t type_info_enum_za_allocation_tag_t_const_data = {
	.name = "za_allocation_tag_t,",
	.type = TYPE_za_allocation_tag_t,
	.kind = META_TYPE_KIND_Enum,
	.member_count = 7,
	.members = {
		.ZA_TAG_NONE = {.name = "ZA_TAG_NONE", .type = TYPE_za_allocation_tag_t, .kind = META_TYPE_KIND_Enum, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(ZA_TAG_NONE), .offset = ZA_TAG_NONE},
		.ZA_TAG_STATIC = {.name = "ZA_TAG_STATIC", .type = TYPE_za_allocation_tag_t, .kind = META_TYPE_KIND_Enum, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(ZA_TAG_STATIC), .offset = ZA_TAG_STATIC},
		.ZA_TAG_TEXTURE = {.name = "ZA_TAG_TEXTURE", .type = TYPE_za_allocation_tag_t, .kind = META_TYPE_KIND_Enum, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(ZA_TAG_TEXTURE), .offset = ZA_TAG_TEXTURE},
		.ZA_TAG_SOUND = {.name = "ZA_TAG_SOUND", .type = TYPE_za_allocation_tag_t, .kind = META_TYPE_KIND_Enum, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(ZA_TAG_SOUND), .offset = ZA_TAG_SOUND},
		.ZA_TAG_FONT = {.name = "ZA_TAG_FONT", .type = TYPE_za_allocation_tag_t, .kind = META_TYPE_KIND_Enum, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(ZA_TAG_FONT), .offset = ZA_TAG_FONT},
		.ZA_TAG_PURGELEVEL = {.name = "ZA_TAG_PURGELEVEL", .type = TYPE_za_allocation_tag_t, .kind = META_TYPE_KIND_Enum, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(ZA_TAG_PURGELEVEL), .offset = ZA_TAG_PURGELEVEL},
		.ZA_TAG_CACHE = {.name = "ZA_TAG_CACHE", .type = TYPE_za_allocation_tag_t, .kind = META_TYPE_KIND_Enum, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(ZA_TAG_CACHE), .offset = ZA_TAG_CACHE},
	}
};

type_info_t GENERATED_type_table[] = {
	{.name = "za_allocation_tag_t", .type = TYPE_za_allocation_tag_t, .size = sizeof(za_allocation_tag_t), .struct_info = (type_info_struct_t*)&type_info_struct_za_allocation_tag_t_const_data},
	{.name = "u32", .type = TYPE_u32, .size = sizeof(u32), .struct_info = null},
	{.name = "bool8", .type = TYPE_bool8, .size = sizeof(bool8), .struct_info = null},
	{.name = "u64", .type = TYPE_u64, .size = sizeof(u64), .struct_info = null},
	{.name = "zone_allocator_block_t", .type = TYPE_zone_allocator_block_t, .size = sizeof(zone_allocator_block_t), .struct_info = (type_info_struct_t*)&type_info_struct_zone_allocator_block_t_const_data},
	{.name = "sys_mutex_t", .type = TYPE_sys_mutex_t, .size = sizeof(sys_mutex_t), .struct_info = null},
	{.name = "u8", .type = TYPE_u8, .size = sizeof(u8), .struct_info = null},
	{.name = "zone_allocator_block_t", .type = TYPE_zone_allocator_block_t, .size = sizeof(zone_allocator_block_t), .struct_info = null},
	{.name = "zone_allocator_t", .type = TYPE_zone_allocator_t, .size = sizeof(zone_allocator_t), .struct_info = (type_info_struct_t*)&type_info_struct_zone_allocator_t_const_data},
};


string_t
c_meta_get_type_string_from_enum(GENERATED_program_type_t type_enum)
{
    string_t result = {};
    switch(type_enum)
    {
#define X(enum, string)           \
        case enum:                \
        {                         \
            result = STR(string); \
            goto exit;            \
        }break;                   

    GENERATED_PROGRAM_TYPE_LIST(X)
#undef X
    }
exit:
    return(result);
}


GENERATED_program_type_t 
c_meta_get_type_enum_from_string(string_t type_string)
{
    GENERATED_program_type_t result = (GENERATED_program_type_t)0;
#define X(enum, string)                                           \
    if(memcmp(string, type_string.data, sizeof(string) - 1) == 0) \
    {                                                             \
        result = enum;                                            \
        goto exit;                                                \
    }                                                             \
    GENERATED_PROGRAM_TYPE_LIST(X)
#undef X

exit:
    return(result);
}

string_t 
c_meta_get_type_kind_string_from_enum(metatype_kind_t kind)
{
    string_t result = {};
    switch(kind)
    {
#define X(enum, string)                                                                 \
        case enum:                                                                      \
        {                                                                               \
            result = c_string_make_copy(&global_context->temporary_arena, STR(string)); \
            goto exit;                                                                  \
        }break; 

    METATYPE_KIND_LIST(X)
#undef X
    }
exit:
    return(result);
}

metatype_kind_t
c_meta_get_type_kind_enum_from_string(string_t kind_string)
{
    metatype_kind_t result = {};
#define X(enum, string)                                           \
    if(memcmp(string, kind_string.data, sizeof(string) - 1) == 0) \
    {                                                             \
        result = enum;                                            \
        goto exit;                                                \
    }                                                             \

    METATYPE_KIND_LIST(X)
#undef X
exit:
    return(result);
}

string_t
c_meta_get_type_flag_string_from_enum(metatype_flags_t flag)
{
    string_t result = {};
    switch(flag)
    {
#define X(enum, value, string)                                                          \
        case enum:                                                                      \
        {                                                                               \
            result = c_string_make_copy(&global_context->temporary_arena, STR(string)); \
            goto exit;                                                                  \
        }break; 

    METATYPE_FLAG_LIST(X)
#undef X
    }
exit:
    return(result);
}

metatype_flags_t
c_meta_get_type_flag_enum_from_string(string_t flag_name)
{
    metatype_flags_t result = {};
#define X(enum, value, string)                                  \
    if(memcmp(string, flag_name.data, sizeof(string) - 1) == 0) \
    {                                                           \
        result = enum;                                          \
        goto exit;                                              \
    }                                                           \

    METATYPE_FLAG_LIST(X)
#undef X
exit:
    return(result);
}

meta_struct_type_t
c_meta_get_struct_type_class_from_string(string_t type)
{
    meta_struct_type_t result = META_STRUCT_TYPE_Invalid;
#define X(enum, string)                                    \
    if(memcmp(string, type.data, sizeof(string) - 1) == 0) \
    {                                                      \
        result = enum;                                     \
        goto exit;                                         \
    }                                                      \

    META_STRUCT_TYPE_LIST(X)
#undef X

exit:
    return(result);
}

string_t
c_meta_get_struct_type_class_from_enum(meta_struct_type_t type)
{
    string_t result = {};
    switch(type)
    {
#define X(enum, string)                                                                 \
        case enum:                                                                      \
        {                                                                               \
            result = c_string_make_copy(&global_context->temporary_arena, STR(string)); \
            goto exit;                                                                  \
        }break; 

    META_STRUCT_TYPE_LIST(X)
#undef X
    }
exit:
    return(result);
}

type_info_t*
c_meta_get_type_info_by_name(string_t type)
{
    type_info_t *result = null;

    GENERATED_program_type_t type_enum = c_meta_get_type_enum_from_string(type);
    result = &GENERATED_type_table[type_enum];

    return(result);
}

type_info_t*
c_meta_get_type_info_by_enum(GENERATED_program_type_t type_enum)
{
    type_info_t *result = null;
    result = &GENERATED_type_table[type_enum];

    return(result);
});

type_info_member_t*
c_meta_get_member_info(type_info_struct_t *struct_info, string_t member_name)
{
    type_info_member_t *result = null;
    for(u32 member_index = 0;
        member_index < struct_info->member_count;
        ++member_index)
    {
        found = struct_info->members + member_index;
        if(c_string_compare(STR(found->name), member_name))
        {
            found = result;
            break;
        }
    }

    return(result);
}

type_info_struct_t*
c_meta_get_struct_info(string_t structure_type_name)
{
    type_info_struct_t *result = null;
    type_info_t *type = c_meta_get_type_info_by_name(structure_type_name);
    result = type->struct_info;

    return(result);
}

#endif

