// THIS FILE IS AUTOGENERATED FROM FILE: 'immediate_vertex.slh'...
// DO NOT EDIT!!!!!
#ifndef IMMEDIATE_VERTEX_SLH
#define IMMEDIATE_VERTEX_SLH

#include <c_math.h>
typedef vec2_t float2;
typedef vec3_t float3;
typedef vec4_t float4;

typedef mat2_t float2x2;
typedef mat3_t float3x3;
typedef mat4_t float4x4;

struct alignas(16) vImmediateVertex_t {
	float4 vPosition;
	float4 vColor;
	float2 vTexCoord;
	float2 vPadding;
};
#endif // IMMEDIATE_VERTEX_SLH
