// THIS FILE IS GENERATED BY METAPROGRAM.EXE...
// IT CONTAINS ALL THE RTTI NEEDED FOR THE PROGRAM...

#if !defined(GENERATED_PROGRAM_RTTI_H)
#define GENERATED_PROGRAM_RTTI_H

#define GENERATED_PROGRAM_TYPE_LIST(X) \
	X(TYPE_u32, "u32") \
	X(TYPE_string_t, "string_t") \
	X(TYPE_s32, "s32") \
	X(TYPE_other_thing_t, "other_thing_t") \
	X(TYPE_test_structure_t, "test_structure_t") \
	X(TYPE_test_thing_t, "test_thing_t") \


enum GENERATED_program_type_t { 
#define X(enum, string) enum,  
GENERATED_PROGRAM_TYPE_LIST(X)
#undef X
};


#define META_STRUCT_TYPE_LIST(X) \
    X(META_STRUCT_TYPE_Struct, "struct") \
    X(META_STRUCT_TYPE_Union,  "union") \
    X(META_STRUCT_TYPE_Enum,   "enum")

typedef enum meta_struct_type 
{
    META_STRUCT_TYPE_Invalid,

#define X(enum, string) enum, 
    META_STRUCT_TYPE_LIST(X)
#undef X

    META_STRUCT_TYPE_Count
}meta_struct_type_t;

#define METATYPE_KIND_LIST(X) \
    X(META_TYPE_KIND_Primitive,    "META_TYPE_KIND_Primitive") \
    X(META_TYPE_KIND_Struct,       "META_TYPE_KIND_Struct") \
    X(META_TYPE_KIND_Enum,         "META_TYPE_KIND_Enum") \
    X(META_TYPE_KIND_Array,        "META_TYPE_KIND_Array") \
    X(META_TYPE_KIND_DynamicArray, "META_TYPE_KIND_DynamicArray") \
    X(META_TYPE_KIND_HashTable,    "META_TYPE_KIND_HashTable") \
    X(META_TYPE_KIND_Invalid,      "META_TYPE_KIND_Invalid") 

typedef enum metatype_kind
{
    // NOTE(Sleepster): Default to primitive 
#define X(enum, string) enum,
    METATYPE_KIND_LIST(X)
#undef X

    META_TYPE_KIND_Count
}metatype_kind_t;

#define METATYPE_FLAG_LIST(X) \
    X(META_TYPE_FLAGS_None,      1u << 0, "META_TYPE_FLAGS_None") \
    X(META_TYPE_FLAGS_Constant,  1u << 1, "META_TYPE_FLAGS_Constant") \
    X(META_TYPE_FLAGS_Volatile,  1u << 2, "META_TYPE_FLAGS_Volatile") \
    X(META_TYPE_FLAGS_Static,    1u << 3, "META_TYPE_FLAGS_Static") \
    X(META_TYPE_FLAGS_Pointer,   1u << 4, "META_TYPE_FLAGS_Pointer") \
    X(META_TYPE_FLAGS_Anonymous, 1u << 5, "META_TYPE_FLAGS_Anonymous")

typedef enum metatype_flags
{
#define X(enum, value, string) enum = value,
    METATYPE_FLAG_LIST(X)
#undef X

    META_TYPE_FLAGS_Count
}metatype_flags_t;

typedef struct type_info_member {
    const char     *name; // string
    u32             type; // types enum
                          
    metatype_kind_t kind;
    u32             modifier_flags;
    u32             flag_counter;

    u32             pointer_depth;
    u32             array_size;

    u32             size;
    u32             offset;
}type_info_member_t;

typedef struct type_info_struct {
    const char         *name;           // string
    u32                 type;           // types enum
    metatype_kind_t     kind;           // is it struct? union? enum?
    u32                 modifier_flags; // for anonymous structures

    u32                 size;
    u32                 member_count;
    type_info_member_t *members;
}type_info_struct_t;

typedef struct type_info
{
    const char         *name;
    u32                 type;
    u32                 size;

    type_info_struct_t *struct_info;
}type_info_t;

struct type_info_struct_other_thing_t {
	u32 size;
	u32 member_count;
	union {
		type_info_member_t member_array[2];
		struct {
			type_info_member_t element_inside_other_struct0;
			type_info_member_t element_inside_other_struct1;
		}members;
	};
};

struct type_info_struct_test_structure_t {
	u32 size;
	u32 member_count;
	union {
		type_info_member_t member_array[2];
		struct {
			type_info_member_t test_element;
			type_info_member_t other_test_element;
		}members;
	};
};

struct type_info_struct_test_thing_t {
	u32 size;
	u32 member_count;
	union {
		type_info_member_t member_array[4];
		struct {
			type_info_member_t element0;
			type_info_member_t element1;
			type_info_member_t element2;
			type_info_member_t element3;
		}members;
	};
};

struct type_info_struct_test_object {
	u32 size;
	u32 member_count;
	union {
		type_info_member_t member_array[4];
		struct {
			type_info_member_t test_object_element0;
			type_info_member_t test_object_element1;
			type_info_member_t test_object_element2;
			type_info_member_t test_object_element4;
		}members;
	};
};



const static type_info_struct_other_thing_t type_info_struct_other_thing_t_const_data = {
	.name = "other_thing_t,",
	.type = TYPE_other_thing_t,
	.kind = META_TYPE_KIND_Struct,
	.modifier_flags = META_TYPE_FLAGS_None,
	.size = sizeof(other_thing_t),
	.member_count = 2,
	.members = {
		.element_inside_other_struct0 = {.name = "s32", .type = TYPE_s32, .kind = META_TYPE_KIND_Primitive, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(other_thing_t), .offset = offsetof(other_thing_t, element_inside_other_struct0)},
		.element_inside_other_struct1 = {.name = "s32", .type = TYPE_s32, .kind = META_TYPE_KIND_Primitive, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(other_thing_t), .offset = offsetof(other_thing_t, element_inside_other_struct1)},
	}
};
const static type_info_struct_test_structure_t type_info_struct_test_structure_t_const_data = {
	.name = "test_structure_t,",
	.type = TYPE_test_structure_t,
	.kind = META_TYPE_KIND_Struct,
	.modifier_flags = META_TYPE_FLAGS_None,
	.size = sizeof(test_structure_t),
	.member_count = 2,
	.members = {
		.test_element = {.name = "u32", .type = TYPE_u32, .kind = META_TYPE_KIND_Primitive, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(test_structure_t), .offset = offsetof(test_structure_t, test_element)},
		.other_test_element = {.name = "u32", .type = TYPE_u32, .kind = META_TYPE_KIND_Primitive, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(test_structure_t), .offset = offsetof(test_structure_t, other_test_element)},
	}
};
const static type_info_struct_test_thing_t type_info_struct_test_thing_t_const_data = {
	.name = "test_thing_t,",
	.type = TYPE_test_thing_t,
	.kind = META_TYPE_KIND_Struct,
	.modifier_flags = META_TYPE_FLAGS_None,
	.size = sizeof(test_thing_t),
	.member_count = 4,
	.members = {
		.element0 = {.name = "u32", .type = TYPE_u32, .kind = META_TYPE_KIND_Array, .modifier_flags = META_TYPE_FLAGS_Constant, .flag_counter = 1, .pointer_depth = 0, .array_size = 0, .size = sizeof(test_thing_t), .offset = offsetof(test_thing_t, element0)},
		.element1 = {.name = "string_t", .type = TYPE_string_t, .kind = META_TYPE_KIND_DynamicArray, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(test_thing_t), .offset = offsetof(test_thing_t, element1)},
		.element2 = {.name = "s32", .type = TYPE_s32, .kind = META_TYPE_KIND_HashTable, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(test_thing_t), .offset = offsetof(test_thing_t, element2)},
		.element3 = {.name = "u32", .type = TYPE_u32, .kind = META_TYPE_KIND_Primitive, .modifier_flags = META_TYPE_FLAGS_Constant|META_TYPE_FLAGS_Volatile, .flag_counter = 2, .pointer_depth = 0, .array_size = 0, .size = sizeof(test_thing_t), .offset = offsetof(test_thing_t, element3)},
	}
};
const static type_info_struct_test_object type_info_struct_test_object_const_data = {
	.name = "test_object,",
	.type = TYPE_test_object,
	.kind = META_TYPE_KIND_Struct,
	.modifier_flags = META_TYPE_FLAGS_None,
	.size = sizeof(test_object),
	.member_count = 4,
	.members = {
		.test_object_element0 = {.name = "u32", .type = TYPE_u32, .kind = META_TYPE_KIND_Primitive, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(test_object), .offset = offsetof(test_object, test_object_element0)},
		.test_object_element1 = {.name = "u32", .type = TYPE_u32, .kind = META_TYPE_KIND_Primitive, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(test_object), .offset = offsetof(test_object, test_object_element1)},
		.test_object_element2 = {.name = "u32", .type = TYPE_u32, .kind = META_TYPE_KIND_Primitive, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(test_object), .offset = offsetof(test_object, test_object_element2)},
		.test_object_element4 = {.name = "u32", .type = TYPE_u32, .kind = META_TYPE_KIND_Primitive, .modifier_flags = META_TYPE_FLAGS_None, .flag_counter = 0, .pointer_depth = 0, .array_size = 0, .size = sizeof(test_object), .offset = offsetof(test_object, test_object_element4)},
	}
};


type_info_t GENERATED_type_table[] = {
	{.name = "u32", .type = TYPE_u32, .size = sizeof(u32), .struct_info = null},
	{.name = "string_t", .type = TYPE_string_t, .size = sizeof(string_t), .struct_info = null},
	{.name = "s32", .type = TYPE_s32, .size = sizeof(s32), .struct_info = null},
	{.name = "other_thing_t", .type = TYPE_other_thing_t, .size = sizeof(other_thing_t), .struct_info = (type_info_struct_t*)&type_info_struct_other_thing_t_const_data},
	{.name = "test_structure_t", .type = TYPE_test_structure_t, .size = sizeof(test_structure_t), .struct_info = (type_info_struct_t*)&type_info_struct_test_structure_t_const_data},
	{.name = "test_thing_t", .type = TYPE_test_thing_t, .size = sizeof(test_thing_t), .struct_info = (type_info_struct_t*)&type_info_struct_test_thing_t_const_data},
};


string_t
c_meta_get_type_string_from_enum(GENERATED_program_type_t type_enum)
{
    string_t result = {};
    switch(type_enum)
    {
#define X(enum, string)           \
        case enum:                \
        {                         \
            result = STR(string); \
            goto exit;            \
        }break;                   

    GENERATED_PROGRAM_TYPE_LIST(X)
#undef X
    }
exit:
    return(result);
}


GENERATED_program_type_t 
c_meta_get_type_enum_from_string(string_t type_string)
{
    GENERATED_program_type_t result = (GENERATED_program_type_t)0;
#define X(enum, string)                                           \
    if(memcmp(string, type_string.data, sizeof(string) - 1) == 0) \
    {                                                             \
        result = enum;                                            \
        goto exit;                                                \
    }                                                             \
    GENERATED_PROGRAM_TYPE_LIST(X)
#undef X

exit:
    return(result);
}

string_t 
c_meta_get_type_kind_string_from_enum(metatype_kind_t kind)
{
    string_t result = {};
    switch(kind)
    {
#define X(enum, string)                                                                 \
        case enum:                                                                      \
        {                                                                               \
            result = c_string_make_copy(&global_context->temporary_arena, STR(string)); \
            goto exit;                                                                  \
        }break; 

    METATYPE_KIND_LIST(X)
#undef X
    }
exit:
    return(result);
}

metatype_kind_t
c_meta_get_type_kind_enum_from_string(string_t kind_string)
{
    metatype_kind_t result = {};
#define X(enum, string)                                           \
    if(memcmp(string, kind_string.data, sizeof(string) - 1) == 0) \
    {                                                             \
        result = enum;                                            \
        goto exit;                                                \
    }                                                             \

    METATYPE_KIND_LIST(X)
#undef X
exit:
    return(result);
}

string_t
c_meta_get_type_flag_string_from_enum(metatype_flags_t flag)
{
    string_t result = {};
    switch(flag)
    {
#define X(enum, value, string)                                                          \
        case enum:                                                                      \
        {                                                                               \
            result = c_string_make_copy(&global_context->temporary_arena, STR(string)); \
            goto exit;                                                                  \
        }break; 

    METATYPE_FLAG_LIST(X)
#undef X
    }
exit:
    return(result);
}

metatype_flags_t
c_meta_get_type_flag_enum_from_string(string_t flag_name)
{
    metatype_flags_t result = {};
#define X(enum, value, string)                                  \
    if(memcmp(string, flag_name.data, sizeof(string) - 1) == 0) \
    {                                                           \
        result = enum;                                          \
        goto exit;                                              \
    }                                                           \

    METATYPE_FLAG_LIST(X)
#undef X
exit:
    return(result);
}

meta_struct_type_t
c_meta_get_struct_type_class_from_string(string_t type)
{
    meta_struct_type_t result = META_STRUCT_TYPE_Invalid;
#define X(enum, string)                                    \
    if(memcmp(string, type.data, sizeof(string) - 1) == 0) \
    {                                                      \
        result = enum;                                     \
        goto exit;                                         \
    }                                                      \

    META_STRUCT_TYPE_LIST(X)
#undef X

exit:
    return(result);
}

string_t
c_meta_get_struct_type_class_from_enum(meta_struct_type_t type)
{
    string_t result = {};
    switch(type)
    {
#define X(enum, string)                                                                 \
        case enum:                                                                      \
        {                                                                               \
            result = c_string_make_copy(&global_context->temporary_arena, STR(string)); \
            goto exit;                                                                  \
        }break; 

    META_STRUCT_TYPE_LIST(X)
#undef X
    }
exit:
    return(result);
}

type_info_t*
c_meta_get_type_info_by_name(string_t type)
{
    type_info_t *result = null;

    GENERATED_program_type_t type_enum = c_meta_get_type_enum_from_string(type);
    result = &GENERATED_type_table[type_enum];

    return(result);
}

type_info_t*
c_meta_get_type_info_by_enum(GENERATED_program_type_t type_enum)
{
    type_info_t *result = null;
    result = &GENERATED_type_table[type_enum];

    return(result);
});

type_info_member_t*
c_meta_get_member_info(type_info_struct_t *struct_info, string_t member_name)
{
    type_info_member_t *result = null;
    for(u32 member_index = 0;
        member_index < struct_info->member_count;
        ++member_index)
    {
        found = struct_info->members + member_index;
        if(c_string_compare(STR(found->name), member_name))
        {
            found = result;
            break;
        }
    }

    return(result);
}

type_info_struct_t*
c_meta_get_struct_info(string_t structure_type_name)
{
    type_info_struct_t *result = null;
    type_info_t *type = c_meta_get_type_info_by_name(structure_type_name);
    result = type->struct_info;

    return(result);
}

#endif

